SUBDIR=	arithmetic backgammon banner bcd boggle bs caesar canfield \
	cribbage factor fish fortune gomoku grdc hangman mille monop \
	morse number phantasia pig pom ppt primes rain random robots \
	sail snake tetris trek wargames worm worms wump

.include <bsd.subdir.mk>
