SUBDIR=	dev/microcode \
	arch/alpha arch/amd64 arch/armish arch/hp300 \
	arch/hppa arch/hppa64 arch/i386 arch/landisk \
	arch/m68k arch/mac68k arch/macppc arch/sgi \
	arch/sparc arch/sparc64 arch/vax arch/zaurus

.include <bsd.subdir.mk>
