/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.6 2010/02/12 14:25:06 mickey Exp 
 */

/* syscall: "syscall" ret: "int" args: "int" "..." */
#define	SYS_syscall	0

/* syscall: "sched_yield" ret: "int" args: */
#define	SYS_sched_yield	1

/* syscall: "__sysctl" ret: "int" args: "int *" "u_int" "void *" "size_t *" "void *" "size_t" */
#define	SYS___sysctl	2

/* syscall: "exit" ret: "void" args: "int" */
#define	SYS_exit	3

/* syscall: "fork" ret: "int" args: */
#define	SYS_fork	4

/* syscall: "vfork" ret: "int" args: */
#define	SYS_vfork	5

/* syscall: "rfork" ret: "int" args: "int" */
#define	SYS_rfork	6

/* syscall: "wait4" ret: "pid_t" args: "pid_t" "int *" "int" "struct rusage *" */
#define	SYS_wait4	7

/* syscall: "fchdir" ret: "int" args: "int" */
#define	SYS_fchdir	8

/* syscall: "__getcwd" ret: "int" args: "char *" "size_t" */
#define	SYS___getcwd	9

/* syscall: "closefrom" ret: "int" args: "int" */
#define	SYS_closefrom	10

/* syscall: "getpid" ret: "pid_t" args: */
#define	SYS_getpid	11

/* syscall: "mount" ret: "int" args: "const char *" "const char *" "int" "void *" */
#define	SYS_mount	12

/* syscall: "unmount" ret: "int" args: "const char *" "int" */
#define	SYS_unmount	13

/* syscall: "setuid" ret: "int" args: "uid_t" */
#define	SYS_setuid	14

/* syscall: "getuid" ret: "uid_t" args: */
#define	SYS_getuid	15

/* syscall: "geteuid" ret: "uid_t" args: */
#define	SYS_geteuid	16

/* syscall: "recvmsg" ret: "ssize_t" args: "int" "struct msghdr *" "int" */
#define	SYS_recvmsg	17

/* syscall: "sendmsg" ret: "ssize_t" args: "int" "const struct msghdr *" "int" */
#define	SYS_sendmsg	18

/* syscall: "recvfrom" ret: "ssize_t" args: "int" "void *" "size_t" "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_recvfrom	19

/* syscall: "accept" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_accept	20

/* syscall: "getpeername" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_getpeername	21

/* syscall: "getsockname" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_getsockname	22

/* syscall: "kill" ret: "int" args: "int" "int" */
#define	SYS_kill	23

/* syscall: "getppid" ret: "pid_t" args: */
#define	SYS_getppid	24

/* syscall: "dup" ret: "int" args: "int" */
#define	SYS_dup	25

/* syscall: "getegid" ret: "gid_t" args: */
#define	SYS_getegid	26

/* syscall: "profil" ret: "int" args: "caddr_t" "size_t" "u_long" "u_int" */
#define	SYS_profil	27

/* syscall: "sigaction" ret: "int" args: "int" "const struct sigaction *" "struct sigaction *" */
#define	SYS_sigaction	28

/* syscall: "getgid" ret: "gid_t" args: */
#define	SYS_getgid	29

/* syscall: "sigprocmask" ret: "int" args: "int" "sigset_t" */
#define	SYS_sigprocmask	30

/* syscall: "getlogin" ret: "int" args: "char *" "u_int" */
#define	SYS_getlogin	31

/* syscall: "setlogin" ret: "int" args: "const char *" */
#define	SYS_setlogin	32

/* syscall: "sigpending" ret: "int" args: */
#define	SYS_sigpending	33

/* syscall: "sigaltstack" ret: "int" args: "const struct sigaltstack *" "struct sigaltstack *" */
#define	SYS_sigaltstack	34

/* syscall: "ioctl" ret: "int" args: "int" "u_long" "..." */
#define	SYS_ioctl	35

/* syscall: "reboot" ret: "int" args: "int" */
#define	SYS_reboot	36

/* syscall: "revoke" ret: "int" args: "const char *" */
#define	SYS_revoke	37

/* syscall: "execve" ret: "int" args: "const char *" "char *const *" "char *const *" */
#define	SYS_execve	38

/* syscall: "umask" ret: "mode_t" args: "mode_t" */
#define	SYS_umask	39

/* syscall: "chroot" ret: "int" args: "const char *" */
#define	SYS_chroot	40

/* syscall: "issetugid" ret: "int" args: */
#define	SYS_issetugid	41

/* syscall: "adjfreq" ret: "int" args: "const int64_t *" "int64_t *" */
#define	SYS_adjfreq	42

/* syscall: "adjtime" ret: "int" args: "const struct timeval *" "struct timeval *" */
#define	SYS_adjtime	43

/* syscall: "getgroups" ret: "int" args: "int" "gid_t *" */
#define	SYS_getgroups	44

/* syscall: "setgroups" ret: "int" args: "int" "const gid_t *" */
#define	SYS_setgroups	45

/* syscall: "getpgrp" ret: "int" args: */
#define	SYS_getpgrp	46

/* syscall: "setpgid" ret: "int" args: "pid_t" "int" */
#define	SYS_setpgid	47

/* syscall: "setitimer" ret: "int" args: "int" "const struct itimerval *" "struct itimerval *" */
#define	SYS_setitimer	48

/* syscall: "getitimer" ret: "int" args: "int" "struct itimerval *" */
#define	SYS_getitimer	49

/* syscall: "dup2" ret: "int" args: "int" "int" */
#define	SYS_dup2	50

/* syscall: "getpeereid" ret: "int" args: "int" "uid_t *" "gid_t *" */
#define	SYS_getpeereid	51

/* syscall: "setpriority" ret: "int" args: "int" "id_t" "int" */
#define	SYS_setpriority	52

/* syscall: "socket" ret: "int" args: "int" "int" "int" */
#define	SYS_socket	53

/* syscall: "connect" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_connect	54

/* syscall: "getpriority" ret: "int" args: "int" "id_t" */
#define	SYS_getpriority	55

/* syscall: "sigreturn" ret: "int" args: "struct sigcontext *" */
#define	SYS_sigreturn	56

/* syscall: "bind" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_bind	57

/* syscall: "setsockopt" ret: "int" args: "int" "int" "int" "const void *" "socklen_t" */
#define	SYS_setsockopt	58

/* syscall: "listen" ret: "int" args: "int" "int" */
#define	SYS_listen	59

/* syscall: "sigsuspend" ret: "int" args: "int" */
#define	SYS_sigsuspend	60

/* syscall: "gettimeofday" ret: "int" args: "struct timeval *" "struct timezone *" */
#define	SYS_gettimeofday	61

/* syscall: "getrusage" ret: "int" args: "int" "struct rusage *" */
#define	SYS_getrusage	62

/* syscall: "getsockopt" ret: "int" args: "int" "int" "int" "void *" "socklen_t *" */
#define	SYS_getsockopt	63

/* syscall: "settimeofday" ret: "int" args: "const struct timeval *" "const struct timezone *" */
#define	SYS_settimeofday	64

/* syscall: "setreuid" ret: "int" args: "uid_t" "uid_t" */
#define	SYS_setreuid	65

/* syscall: "setregid" ret: "int" args: "gid_t" "gid_t" */
#define	SYS_setregid	66

/* syscall: "flock" ret: "int" args: "int" "int" */
#define	SYS_flock	67

/* syscall: "sendto" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_sendto	68

/* syscall: "shutdown" ret: "int" args: "int" "int" */
#define	SYS_shutdown	69

/* syscall: "socketpair" ret: "int" args: "int" "int" "int" "int *" */
#define	SYS_socketpair	70

/* syscall: "getsid" ret: "pid_t" args: "pid_t" */
#define	SYS_getsid	71

/* syscall: "setsid" ret: "int" args: */
#define	SYS_setsid	72

/* syscall: "quotactl" ret: "int" args: "const char *" "int" "int" "char *" */
#define	SYS_quotactl	73

/* syscall: "sync" ret: "void" args: */
#define	SYS_sync	74

/* syscall: "sysarch" ret: "int" args: "int" "void *" */
#define	SYS_sysarch	75

/* syscall: "setgid" ret: "int" args: "gid_t" */
#define	SYS_setgid	76

/* syscall: "setegid" ret: "int" args: "gid_t" */
#define	SYS_setegid	77

/* syscall: "seteuid" ret: "int" args: "uid_t" */
#define	SYS_seteuid	78

/* syscall: "mknod" ret: "int" args: "const char *" "mode_t" "dev_t" */
#define	SYS_mknod	79

/* syscall: "mkfifo" ret: "int" args: "const char *" "mode_t" */
#define	SYS_mkfifo	80

/* syscall: "mkdir" ret: "int" args: "const char *" "mode_t" */
#define	SYS_mkdir	81

/* syscall: "rmdir" ret: "int" args: "const char *" */
#define	SYS_rmdir	82

/* syscall: "symlink" ret: "int" args: "const char *" "const char *" */
#define	SYS_symlink	83

/* syscall: "readlink" ret: "int" args: "const char *" "char *" "size_t" */
#define	SYS_readlink	84

/* syscall: "rename" ret: "int" args: "const char *" "const char *" */
#define	SYS_rename	85

/* syscall: "link" ret: "int" args: "const char *" "const char *" */
#define	SYS_link	86

/* syscall: "unlink" ret: "int" args: "const char *" */
#define	SYS_unlink	87

/* syscall: "fpathconf" ret: "long" args: "int" "int" */
#define	SYS_fpathconf	89

/* syscall: "swapctl" ret: "int" args: "int" "const void *" "int" */
#define	SYS_swapctl	90

/* syscall: "getrlimit" ret: "int" args: "int" "struct rlimit *" */
#define	SYS_getrlimit	91

/* syscall: "setrlimit" ret: "int" args: "int" "const struct rlimit *" */
#define	SYS_setrlimit	92

/* syscall: "getdirentries" ret: "int" args: "int" "char *" "int" "long *" */
#define	SYS_getdirentries	93

/* syscall: "lseek" ret: "off_t" args: "int" "int" "off_t" "int" */
#define	SYS_lseek	94

/* syscall: "getpgid" ret: "pid_t" args: "pid_t" */
#define	SYS_getpgid	95

/* syscall: "xfspioctl" ret: "int" args: "int" "char *" "int" "struct ViceIoctl *" "int" */
#define	SYS_xfspioctl	96

/* syscall: "clock_gettime" ret: "int" args: "clockid_t" "struct timespec *" */
#define	SYS_clock_gettime	97

/* syscall: "clock_settime" ret: "int" args: "clockid_t" "const struct timespec *" */
#define	SYS_clock_settime	98

/* syscall: "clock_getres" ret: "int" args: "clockid_t" "struct timespec *" */
#define	SYS_clock_getres	99

/* syscall: "mmap" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	SYS_mmap	105

/* syscall: "munmap" ret: "int" args: "void *" "size_t" */
#define	SYS_munmap	106

/* syscall: "mprotect" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_mprotect	107

/* syscall: "madvise" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_madvise	108

/* syscall: "mincore" ret: "int" args: "void *" "size_t" "char *" */
#define	SYS_mincore	109

/* syscall: "mlock" ret: "int" args: "const void *" "size_t" */
#define	SYS_mlock	110

/* syscall: "munlock" ret: "int" args: "const void *" "size_t" */
#define	SYS_munlock	111

/* syscall: "mlockall" ret: "int" args: "int" */
#define	SYS_mlockall	112

/* syscall: "munlockall" ret: "int" args: */
#define	SYS_munlockall	113

/* syscall: "minherit" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_minherit	114

/* syscall: "msync" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_msync	115

/* syscall: "mquery" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	SYS_mquery	116

/* syscall: "nanosleep" ret: "int" args: "const struct timespec *" "struct timespec *" */
#define	SYS_nanosleep	117

/* syscall: "poll" ret: "int" args: "struct pollfd *" "u_int" "int" */
#define	SYS_poll	118

/* syscall: "select" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "struct timeval *" */
#define	SYS_select	119

/* syscall: "pipe" ret: "int" args: "int *" */
#define	SYS_pipe	120

/* syscall: "kqueue" ret: "int" args: */
#define	SYS_kqueue	121

/* syscall: "kevent" ret: "int" args: "int" "const struct kevent *" "int" "struct kevent *" "int" "const struct timespec *" */
#define	SYS_kevent	122

/* syscall: "getresuid" ret: "int" args: "uid_t *" "uid_t *" "uid_t *" */
#define	SYS_getresuid	123

/* syscall: "setresuid" ret: "int" args: "uid_t" "uid_t" "uid_t" */
#define	SYS_setresuid	124

/* syscall: "getresgid" ret: "int" args: "gid_t *" "gid_t *" "gid_t *" */
#define	SYS_getresgid	125

/* syscall: "setresgid" ret: "int" args: "gid_t" "gid_t" "gid_t" */
#define	SYS_setresgid	126

/* syscall: "getfsstat" ret: "int" args: "struct statfs *" "size_t" "int" */
#define	SYS_getfsstat	127

/* syscall: "fstatfs" ret: "int" args: "int" "struct statfs *" */
#define	SYS_fstatfs	128

/* syscall: "nfssvc" ret: "int" args: "int" "void *" */
#define	SYS_nfssvc	167

/* syscall: "acct" ret: "int" args: "const char *" */
#define	SYS_acct	168

/* syscall: "ptrace" ret: "int" args: "int" "pid_t" "caddr_t" "int" */
#define	SYS_ptrace	169

/* syscall: "ktrace" ret: "int" args: "const char *" "int" "int" "pid_t" */
#define	SYS_ktrace	170

/* syscall: "semget" ret: "int" args: "key_t" "int" "int" */
#define	SYS_semget	171

/* syscall: "semop" ret: "int" args: "int" "struct sembuf *" "size_t" */
#define	SYS_semop	172

/* syscall: "__semctl" ret: "int" args: "int" "int" "int" "union semun *" */
#define	SYS___semctl	173

/* syscall: "shmget" ret: "int" args: "key_t" "size_t" "int" */
#define	SYS_shmget	174

/* syscall: "shmctl" ret: "int" args: "int" "int" "struct shmid_ds *" */
#define	SYS_shmctl	175

/* syscall: "shmat" ret: "void *" args: "int" "const void *" "int" */
#define	SYS_shmat	176

/* syscall: "shmdt" ret: "int" args: "const void *" */
#define	SYS_shmdt	177

/* syscall: "msgget" ret: "int" args: "key_t" "int" */
#define	SYS_msgget	178

/* syscall: "msgsnd" ret: "int" args: "int" "const void *" "size_t" "int" */
#define	SYS_msgsnd	179

/* syscall: "msgrcv" ret: "int" args: "int" "void *" "size_t" "long" "int" */
#define	SYS_msgrcv	180

/* syscall: "msgctl" ret: "int" args: "int" "int" "struct msqid_ds *" */
#define	SYS_msgctl	181

/* syscall: "getthrid" ret: "pid_t" args: */
#define	SYS_getthrid	182

/* syscall: "thrsleep" ret: "int" args: "void *" "int" "void *" */
#define	SYS_thrsleep	183

/* syscall: "thrwakeup" ret: "int" args: "void *" "int" */
#define	SYS_thrwakeup	184

/* syscall: "threxit" ret: "int" args: "int" */
#define	SYS_threxit	185

/* syscall: "thrsigdivert" ret: "int" args: "sigset_t" */
#define	SYS_thrsigdivert	186

/* syscall: "__syscall" ret: "quad_t" args: "quad_t" "..." */
#define	SYS___syscall	198

/* syscall: "fhstatfs" ret: "int" args: "const fhandle_t *" "struct statfs *" */
#define	SYS_fhstatfs	220

/* syscall: "getfh" ret: "int" args: "const char *" "fhandle_t *" */
#define	SYS_getfh	221

/* syscall: "fhopen" ret: "int" args: "const fhandle_t *" "int" */
#define	SYS_fhopen	222

/* syscall: "fhstat" ret: "int" args: "const fhandle_t *" "struct stat *" */
#define	SYS_fhstat	223

/* syscall: "open" ret: "int" args: "const char *" "int" "..." */
#define	SYS_open	224

/* syscall: "read" ret: "ssize_t" args: "int" "void *" "size_t" */
#define	SYS_read	225

/* syscall: "write" ret: "ssize_t" args: "int" "const void *" "size_t" */
#define	SYS_write	226

/* syscall: "readv" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	SYS_readv	227

/* syscall: "writev" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	SYS_writev	228

/* syscall: "pread" ret: "ssize_t" args: "int" "void *" "size_t" "int" "off_t" */
#define	SYS_pread	229

/* syscall: "pwrite" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "off_t" */
#define	SYS_pwrite	230

/* syscall: "preadv" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	SYS_preadv	231

/* syscall: "pwritev" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	SYS_pwritev	232

/* syscall: "fsync" ret: "int" args: "int" */
#define	SYS_fsync	233

/* syscall: "fstat" ret: "int" args: "int" "struct stat *" */
#define	SYS_fstat	234

/* syscall: "ftruncate" ret: "int" args: "int" "int" "off_t" */
#define	SYS_ftruncate	235

/* syscall: "futimes" ret: "int" args: "int" "const struct timeval *" */
#define	SYS_futimes	236

/* syscall: "fchmod" ret: "int" args: "int" "mode_t" */
#define	SYS_fchmod	237

/* syscall: "fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	SYS_fchown	238

/* syscall: "fchflags" ret: "int" args: "int" "u_int" */
#define	SYS_fchflags	239

/* syscall: "close" ret: "int" args: "int" */
#define	SYS_close	240

/* syscall: "chdir" ret: "int" args: "const char *" */
#define	SYS_chdir	241

/* syscall: "pathconf" ret: "long" args: "const char *" "int" */
#define	SYS_pathconf	242

/* syscall: "access" ret: "int" args: "const char *" "int" */
#define	SYS_access	243

/* syscall: "stat" ret: "int" args: "const char *" "struct stat *" */
#define	SYS_stat	244

/* syscall: "lstat" ret: "int" args: "const char *" "struct stat *" */
#define	SYS_lstat	245

/* syscall: "statfs" ret: "int" args: "const char *" "struct statfs *" */
#define	SYS_statfs	246

/* syscall: "truncate" ret: "int" args: "const char *" "int" "off_t" */
#define	SYS_truncate	247

/* syscall: "utimes" ret: "int" args: "const char *" "const struct timeval *" */
#define	SYS_utimes	248

/* syscall: "chmod" ret: "int" args: "const char *" "mode_t" */
#define	SYS_chmod	249

/* syscall: "chown" ret: "int" args: "const char *" "uid_t" "gid_t" */
#define	SYS_chown	250

/* syscall: "lchown" ret: "int" args: "const char *" "uid_t" "gid_t" */
#define	SYS_lchown	251

/* syscall: "chflags" ret: "int" args: "const char *" "u_int" */
#define	SYS_chflags	252

/* syscall: "fcntl" ret: "int" args: "int" "int" "..." */
#define	SYS_fcntl	253

				/* 254 is compat_44 getfsstat */

				/* 254 is compat_44 statfs */

				/* 254 is compat_44 fstatfs */

				/* 254 is compat_44 semsys */

				/* 254 is compat_44 __semctl */

				/* 254 is compat_44 msgsys */

				/* 254 is compat_44 msgctl */

				/* 254 is compat_44 shmsys */

				/* 254 is compat_44 shmctl */

				/* 254 is compat_44 getdomainname */

				/* 254 is compat_44 setdomainname */

				/* 254 is compat_44 stat */

				/* 254 is compat_44 lstat */

				/* 254 is compat_44 fstat */

				/* 254 is compat_44 fhstat */

				/* 254 is compat_44 osigaltstack */

				/* 254 is compat_43 sstk */

				/* 254 is compat_43 sbrk */

				/* 254 is compat_43 opipe */

				/* 254 is compat_43 creat */

				/* 254 is compat_43 lseek */

				/* 254 is compat_43 stat */

				/* 254 is compat_43 lstat */

				/* 254 is compat_43 fstat */

				/* 254 is compat_43 getkerninfo */

				/* 254 is compat_43 getpagesize */

				/* 254 is compat_43 mmap */

				/* 254 is compat_43 wait */

				/* 254 is compat_43 gethostname */

				/* 254 is compat_43 sethostname */

				/* 254 is compat_43 ogetdtablesize */

				/* 254 is compat_43 accept */

				/* 254 is compat_43 send */

				/* 254 is compat_43 recv */

				/* 254 is compat_43 sigvec */

				/* 254 is compat_43 sigblock */

				/* 254 is compat_43 sigsetmask */

				/* 254 is compat_43 sigstack */

				/* 254 is compat_43 recvmsg */

				/* 254 is compat_43 sendmsg */

				/* 254 is compat_43 recvfrom */

				/* 254 is compat_43 truncate */

				/* 254 is compat_43 ftruncate */

				/* 254 is compat_43 getpeername */

				/* 254 is compat_43 gethostid */

				/* 254 is compat_43 sethostid */

				/* 254 is compat_43 getrlimit */

				/* 254 is compat_43 setrlimit */

				/* 254 is compat_43 killpg */

				/* 254 is compat_43 quota */

				/* 254 is compat_43 getsockname */

				/* 254 is compat_43 getdirentries */

				/* 254 is compat_43 swapon */

				/* 254 is compat_43 obreak */

#define	SYS_MAXSYSCALL	254
