/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.7 2010/02/15 09:42:19 mickey Exp 
 */

/* syscall: "syscall" ret: "int" args: "int" "..." */
#define	SYS_syscall	0

/* syscall: "sched_yield" ret: "int" args: */
#define	SYS_sched_yield	1

/* syscall: "__sysctl" ret: "int" args: "int *" "u_int" "void *" "size_t *" "void *" "size_t" */
#define	SYS___sysctl	2

/* syscall: "exit" ret: "void" args: "int" */
#define	SYS_exit	3

/* syscall: "fork" ret: "int" args: */
#define	SYS_fork	4

/* syscall: "vfork" ret: "int" args: */
#define	SYS_vfork	5

/* syscall: "rfork" ret: "int" args: "int" */
#define	SYS_rfork	6

/* syscall: "wait4" ret: "pid_t" args: "pid_t" "int *" "int" "struct rusage *" */
#define	SYS_wait4	7

/* syscall: "fchdir" ret: "int" args: "int" */
#define	SYS_fchdir	8

/* syscall: "__getcwd" ret: "int" args: "char *" "size_t" */
#define	SYS___getcwd	9

/* syscall: "closefrom" ret: "int" args: "int" */
#define	SYS_closefrom	10

/* syscall: "mount" ret: "int" args: "const char *" "const char *" "int" "void *" */
#define	SYS_mount	12

/* syscall: "unmount" ret: "int" args: "const char *" "int" */
#define	SYS_unmount	13

/* syscall: "setuid" ret: "int" args: "uid_t" */
#define	SYS_setuid	14

/* syscall: "getpgid" ret: "pid_t" args: "pid_t" */
#define	SYS_getpgid	15

/* syscall: "mmap" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	SYS_mmap	16

/* syscall: "munmap" ret: "int" args: "void *" "size_t" */
#define	SYS_munmap	17

/* syscall: "mprotect" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_mprotect	18

/* syscall: "madvise" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_madvise	19

/* syscall: "mincore" ret: "int" args: "void *" "size_t" "char *" */
#define	SYS_mincore	20

/* syscall: "mlock" ret: "int" args: "const void *" "size_t" */
#define	SYS_mlock	21

/* syscall: "munlock" ret: "int" args: "const void *" "size_t" */
#define	SYS_munlock	22

/* syscall: "mlockall" ret: "int" args: "int" */
#define	SYS_mlockall	23

/* syscall: "munlockall" ret: "int" args: */
#define	SYS_munlockall	24

/* syscall: "minherit" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_minherit	25

/* syscall: "msync" ret: "int" args: "void *" "size_t" "int" */
#define	SYS_msync	26

/* syscall: "mquery" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	SYS_mquery	27

/* syscall: "chroot" ret: "int" args: "const char *" */
#define	SYS_chroot	28

/* syscall: "umask" ret: "mode_t" args: "mode_t" */
#define	SYS_umask	29

/* syscall: "execve" ret: "int" args: "const char *" "char *const *" "char *const *" */
#define	SYS_execve	30

/* syscall: "kill" ret: "int" args: "int" "int" */
#define	SYS_kill	31

/* syscall: "profil" ret: "int" args: "caddr_t" "size_t" "u_long" "u_int" */
#define	SYS_profil	32

/* syscall: "sigaction" ret: "int" args: "int" "const struct sigaction *" "struct sigaction *" */
#define	SYS_sigaction	33

/* syscall: "sigprocmask" ret: "int" args: "int" "sigset_t" */
#define	SYS_sigprocmask	34

/* syscall: "nanosleep" ret: "int" args: "const struct timespec *" "struct timespec *" */
#define	SYS_nanosleep	35

/* syscall: "poll" ret: "int" args: "struct pollfd *" "u_int" "int" */
#define	SYS_poll	36

/* syscall: "select" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "struct timeval *" */
#define	SYS_select	37

/* syscall: "setlogin" ret: "int" args: "const char *" */
#define	SYS_setlogin	38

/* syscall: "sigaltstack" ret: "int" args: "const struct sigaltstack *" "struct sigaltstack *" */
#define	SYS_sigaltstack	39

/* syscall: "ioctl" ret: "int" args: "int" "u_long" "..." */
#define	SYS_ioctl	40

/* syscall: "reboot" ret: "int" args: "int" */
#define	SYS_reboot	41

/* syscall: "revoke" ret: "int" args: "const char *" */
#define	SYS_revoke	42

/* syscall: "setpriority" ret: "int" args: "int" "id_t" "int" */
#define	SYS_setpriority	43

/* syscall: "getpriority" ret: "int" args: "int" "id_t" */
#define	SYS_getpriority	44

/* syscall: "sigreturn" ret: "int" args: "struct sigcontext *" */
#define	SYS_sigreturn	45

/* syscall: "adjfreq" ret: "int" args: "const int64_t *" "int64_t *" */
#define	SYS_adjfreq	46

/* syscall: "adjtime" ret: "int" args: "const struct timeval *" "struct timeval *" */
#define	SYS_adjtime	47

/* syscall: "gettimeofday" ret: "int" args: "struct timeval *" "struct timezone *" */
#define	SYS_gettimeofday	48

/* syscall: "sigsuspend" ret: "int" args: "int" */
#define	SYS_sigsuspend	49

/* syscall: "setgroups" ret: "int" args: "int" "const gid_t *" */
#define	SYS_setgroups	50

/* syscall: "setpgid" ret: "int" args: "pid_t" "int" */
#define	SYS_setpgid	51

/* syscall: "setitimer" ret: "int" args: "int" "const struct itimerval *" "struct itimerval *" */
#define	SYS_setitimer	52

/* syscall: "getitimer" ret: "int" args: "int" "struct itimerval *" */
#define	SYS_getitimer	53

/* syscall: "settimeofday" ret: "int" args: "const struct timeval *" "const struct timezone *" */
#define	SYS_settimeofday	54

/* syscall: "setreuid" ret: "int" args: "uid_t" "uid_t" */
#define	SYS_setreuid	55

/* syscall: "setregid" ret: "int" args: "gid_t" "gid_t" */
#define	SYS_setregid	56

/* syscall: "sendto" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_sendto	57

/* syscall: "setsid" ret: "int" args: */
#define	SYS_setsid	58

/* syscall: "quotactl" ret: "int" args: "const char *" "int" "int" "char *" */
#define	SYS_quotactl	59

/* syscall: "sync" ret: "void" args: */
#define	SYS_sync	70

/* syscall: "sysarch" ret: "int" args: "int" "void *" */
#define	SYS_sysarch	71

/* syscall: "setgid" ret: "int" args: "gid_t" */
#define	SYS_setgid	72

/* syscall: "setegid" ret: "int" args: "gid_t" */
#define	SYS_setegid	73

/* syscall: "seteuid" ret: "int" args: "uid_t" */
#define	SYS_seteuid	74

/* syscall: "setresuid" ret: "int" args: "uid_t" "uid_t" "uid_t" */
#define	SYS_setresuid	75

/* syscall: "setresgid" ret: "int" args: "gid_t" "gid_t" "gid_t" */
#define	SYS_setresgid	76

/* syscall: "getfsstat" ret: "int" args: "struct statfs *" "size_t" "int" */
#define	SYS_getfsstat	77

/* syscall: "rmdir" ret: "int" args: "const char *" */
#define	SYS_rmdir	78

/* syscall: "rename" ret: "int" args: "const char *" "const char *" */
#define	SYS_rename	79

/* syscall: "unlink" ret: "int" args: "const char *" */
#define	SYS_unlink	80

/* syscall: "swapctl" ret: "int" args: "int" "const void *" "int" */
#define	SYS_swapctl	82

/* syscall: "setrlimit" ret: "int" args: "int" "const struct rlimit *" */
#define	SYS_setrlimit	83

/* syscall: "getdirentries" ret: "int" args: "int" "char *" "int" "long *" */
#define	SYS_getdirentries	84

/* syscall: "clock_gettime" ret: "int" args: "clockid_t" "struct timespec *" */
#define	SYS_clock_gettime	85

/* syscall: "clock_settime" ret: "int" args: "clockid_t" "const struct timespec *" */
#define	SYS_clock_settime	86

/* syscall: "clock_getres" ret: "int" args: "clockid_t" "struct timespec *" */
#define	SYS_clock_getres	87

/* syscall: "xfspioctl" ret: "int" args: "int" "char *" "int" "struct ViceIoctl *" "int" */
#define	SYS_xfspioctl	147

/* syscall: "nfssvc" ret: "int" args: "int" "void *" */
#define	SYS_nfssvc	148

/* syscall: "acct" ret: "int" args: "const char *" */
#define	SYS_acct	149

/* syscall: "ptrace" ret: "int" args: "int" "pid_t" "caddr_t" "int" */
#define	SYS_ptrace	150

/* syscall: "ktrace" ret: "int" args: "const char *" "int" "int" "pid_t" */
#define	SYS_ktrace	151

/* syscall: "semget" ret: "int" args: "key_t" "int" "int" */
#define	SYS_semget	152

/* syscall: "semop" ret: "int" args: "int" "struct sembuf *" "size_t" */
#define	SYS_semop	153

/* syscall: "__semctl" ret: "int" args: "int" "int" "int" "union semun *" */
#define	SYS___semctl	154

/* syscall: "shmget" ret: "int" args: "key_t" "size_t" "int" */
#define	SYS_shmget	155

/* syscall: "shmctl" ret: "int" args: "int" "int" "struct shmid_ds *" */
#define	SYS_shmctl	156

/* syscall: "shmat" ret: "void *" args: "int" "const void *" "int" */
#define	SYS_shmat	157

/* syscall: "shmdt" ret: "int" args: "const void *" */
#define	SYS_shmdt	158

/* syscall: "msgget" ret: "int" args: "key_t" "int" */
#define	SYS_msgget	159

/* syscall: "msgsnd" ret: "int" args: "int" "const void *" "size_t" "int" */
#define	SYS_msgsnd	160

/* syscall: "msgrcv" ret: "int" args: "int" "void *" "size_t" "long" "int" */
#define	SYS_msgrcv	161

/* syscall: "msgctl" ret: "int" args: "int" "int" "struct msqid_ds *" */
#define	SYS_msgctl	162

/* syscall: "getthrid" ret: "pid_t" args: */
#define	SYS_getthrid	163

/* syscall: "thrsleep" ret: "int" args: "void *" "int" "void *" */
#define	SYS_thrsleep	164

/* syscall: "thrwakeup" ret: "int" args: "void *" "int" */
#define	SYS_thrwakeup	165

/* syscall: "threxit" ret: "int" args: "int" */
#define	SYS_threxit	166

/* syscall: "thrsigdivert" ret: "int" args: "sigset_t" */
#define	SYS_thrsigdivert	167

/* syscall: "__syscall" ret: "quad_t" args: "quad_t" "..." */
#define	SYS___syscall	198

/* syscall: "getpeereid" ret: "int" args: "int" "uid_t *" "gid_t *" */
#define	SYS_getpeereid	199

/* syscall: "setsockopt" ret: "int" args: "int" "int" "int" "const void *" "socklen_t" */
#define	SYS_setsockopt	200

/* syscall: "getsockopt" ret: "int" args: "int" "int" "int" "void *" "socklen_t *" */
#define	SYS_getsockopt	201

/* syscall: "getpeername" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_getpeername	202

/* syscall: "getsockname" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_getsockname	203

/* syscall: "access" ret: "int" args: "const char *" "int" */
#define	SYS_access	204

/* syscall: "accept" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_accept	205

/* syscall: "listen" ret: "int" args: "int" "int" */
#define	SYS_listen	206

/* syscall: "connect" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_connect	207

/* syscall: "bind" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	SYS_bind	208

/* syscall: "fstatfs" ret: "int" args: "int" "struct statfs *" */
#define	SYS_fstatfs	209

/* syscall: "kqueue" ret: "int" args: */
#define	SYS_kqueue	210

/* syscall: "kevent" ret: "int" args: "int" "const struct kevent *" "int" "struct kevent *" "int" "const struct timespec *" */
#define	SYS_kevent	211

/* syscall: "pipe" ret: "int" args: "int *" */
#define	SYS_pipe	212

/* syscall: "socketpair" ret: "int" args: "int" "int" "int" "int *" */
#define	SYS_socketpair	213

/* syscall: "socket" ret: "int" args: "int" "int" "int" */
#define	SYS_socket	214

/* syscall: "link" ret: "int" args: "const char *" "const char *" */
#define	SYS_link	215

/* syscall: "symlink" ret: "int" args: "const char *" "const char *" */
#define	SYS_symlink	216

/* syscall: "readlink" ret: "int" args: "const char *" "char *" "size_t" */
#define	SYS_readlink	217

/* syscall: "mkfifo" ret: "int" args: "const char *" "mode_t" */
#define	SYS_mkfifo	218

/* syscall: "mkdir" ret: "int" args: "const char *" "mode_t" */
#define	SYS_mkdir	219

/* syscall: "mknod" ret: "int" args: "const char *" "mode_t" "dev_t" */
#define	SYS_mknod	220

/* syscall: "fhstatfs" ret: "int" args: "const fhandle_t *" "struct statfs *" */
#define	SYS_fhstatfs	221

/* syscall: "getfh" ret: "int" args: "const char *" "fhandle_t *" */
#define	SYS_getfh	222

/* syscall: "fhopen" ret: "int" args: "const fhandle_t *" "int" */
#define	SYS_fhopen	223

/* syscall: "fhstat" ret: "int" args: "const fhandle_t *" "struct stat *" */
#define	SYS_fhstat	224

/* syscall: "recvmsg" ret: "ssize_t" args: "int" "struct msghdr *" "int" */
#define	SYS_recvmsg	225

/* syscall: "sendmsg" ret: "ssize_t" args: "int" "const struct msghdr *" "int" */
#define	SYS_sendmsg	226

/* syscall: "recvfrom" ret: "ssize_t" args: "int" "void *" "size_t" "int" "struct sockaddr *" "socklen_t *" */
#define	SYS_recvfrom	227

/* syscall: "open" ret: "int" args: "const char *" "int" "..." */
#define	SYS_open	228

/* syscall: "read" ret: "ssize_t" args: "int" "void *" "size_t" */
#define	SYS_read	229

/* syscall: "write" ret: "ssize_t" args: "int" "const void *" "size_t" */
#define	SYS_write	230

/* syscall: "readv" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	SYS_readv	231

/* syscall: "writev" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	SYS_writev	232

/* syscall: "pread" ret: "ssize_t" args: "int" "void *" "size_t" "int" "off_t" */
#define	SYS_pread	233

/* syscall: "pwrite" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "off_t" */
#define	SYS_pwrite	234

/* syscall: "preadv" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	SYS_preadv	235

/* syscall: "pwritev" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	SYS_pwritev	236

/* syscall: "fsync" ret: "int" args: "int" */
#define	SYS_fsync	237

/* syscall: "fstat" ret: "int" args: "int" "struct stat *" */
#define	SYS_fstat	238

/* syscall: "ftruncate" ret: "int" args: "int" "int" "off_t" */
#define	SYS_ftruncate	239

/* syscall: "futimes" ret: "int" args: "int" "const struct timeval *" */
#define	SYS_futimes	240

/* syscall: "fchmod" ret: "int" args: "int" "mode_t" */
#define	SYS_fchmod	241

/* syscall: "fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	SYS_fchown	242

/* syscall: "fchflags" ret: "int" args: "int" "u_int" */
#define	SYS_fchflags	243

/* syscall: "close" ret: "int" args: "int" */
#define	SYS_close	244

/* syscall: "chdir" ret: "int" args: "const char *" */
#define	SYS_chdir	245

/* syscall: "pathconf" ret: "long" args: "const char *" "int" */
#define	SYS_pathconf	246

/* syscall: "stat" ret: "int" args: "const char *" "struct stat *" */
#define	SYS_stat	247

/* syscall: "lstat" ret: "int" args: "const char *" "struct stat *" */
#define	SYS_lstat	248

/* syscall: "statfs" ret: "int" args: "const char *" "struct statfs *" */
#define	SYS_statfs	249

/* syscall: "truncate" ret: "int" args: "const char *" "int" "off_t" */
#define	SYS_truncate	250

/* syscall: "utimes" ret: "int" args: "const char *" "const struct timeval *" */
#define	SYS_utimes	251

/* syscall: "chmod" ret: "int" args: "const char *" "mode_t" */
#define	SYS_chmod	252

/* syscall: "chown" ret: "int" args: "const char *" "uid_t" "gid_t" */
#define	SYS_chown	253

/* syscall: "lchown" ret: "int" args: "const char *" "uid_t" "gid_t" */
#define	SYS_lchown	254

/* syscall: "chflags" ret: "int" args: "const char *" "u_int" */
#define	SYS_chflags	255

/* syscall: "fcntl" ret: "int" args: "int" "int" "..." */
#define	SYS_fcntl	256

/* syscall: "dup" ret: "int" args: "int" */
#define	SYS_dup	257

/* syscall: "dup2" ret: "int" args: "int" "int" */
#define	SYS_dup2	258

/* syscall: "flock" ret: "int" args: "int" "int" */
#define	SYS_flock	259

/* syscall: "fpathconf" ret: "long" args: "int" "int" */
#define	SYS_fpathconf	260

/* syscall: "lseek" ret: "off_t" args: "int" "int" "off_t" "int" */
#define	SYS_lseek	261

/* syscall: "shutdown" ret: "int" args: "int" "int" */
#define	SYS_shutdown	262

/* syscall: "getpid" ret: "pid_t" args: */
#define	SYS_getpid	263

/* syscall: "getuid" ret: "uid_t" args: */
#define	SYS_getuid	264

/* syscall: "geteuid" ret: "uid_t" args: */
#define	SYS_geteuid	265

/* syscall: "getppid" ret: "pid_t" args: */
#define	SYS_getppid	266

/* syscall: "getegid" ret: "gid_t" args: */
#define	SYS_getegid	267

/* syscall: "getgid" ret: "gid_t" args: */
#define	SYS_getgid	268

/* syscall: "getlogin" ret: "int" args: "char *" "u_int" */
#define	SYS_getlogin	269

/* syscall: "sigpending" ret: "int" args: */
#define	SYS_sigpending	270

/* syscall: "issetugid" ret: "int" args: */
#define	SYS_issetugid	271

/* syscall: "getgroups" ret: "int" args: "int" "gid_t *" */
#define	SYS_getgroups	272

/* syscall: "getpgrp" ret: "int" args: */
#define	SYS_getpgrp	273

/* syscall: "getrusage" ret: "int" args: "int" "struct rusage *" */
#define	SYS_getrusage	274

/* syscall: "getsid" ret: "pid_t" args: "pid_t" */
#define	SYS_getsid	275

/* syscall: "getrlimit" ret: "int" args: "int" "struct rlimit *" */
#define	SYS_getrlimit	276

/* syscall: "getresuid" ret: "int" args: "uid_t *" "uid_t *" "uid_t *" */
#define	SYS_getresuid	277

/* syscall: "getresgid" ret: "int" args: "gid_t *" "gid_t *" "gid_t *" */
#define	SYS_getresgid	278

				/* 279 is compat_44 getfsstat */

				/* 279 is compat_44 statfs */

				/* 279 is compat_44 fstatfs */

				/* 279 is compat_44 semsys */

				/* 279 is compat_44 __semctl */

				/* 279 is compat_44 msgsys */

				/* 279 is compat_44 msgctl */

				/* 279 is compat_44 shmsys */

				/* 279 is compat_44 shmctl */

				/* 279 is compat_44 getdomainname */

				/* 279 is compat_44 setdomainname */

				/* 279 is compat_44 stat */

				/* 279 is compat_44 lstat */

				/* 279 is compat_44 fstat */

				/* 279 is compat_44 fhstat */

				/* 279 is compat_44 osigaltstack */

				/* 279 is compat_43 sstk */

				/* 279 is compat_43 sbrk */

				/* 279 is compat_43 opipe */

				/* 279 is compat_43 creat */

				/* 279 is compat_43 lseek */

				/* 279 is compat_43 stat */

				/* 279 is compat_43 lstat */

				/* 279 is compat_43 fstat */

				/* 279 is compat_43 getkerninfo */

				/* 279 is compat_43 getpagesize */

				/* 279 is compat_43 mmap */

				/* 279 is compat_43 wait */

				/* 279 is compat_43 gethostname */

				/* 279 is compat_43 sethostname */

				/* 279 is compat_43 ogetdtablesize */

				/* 279 is compat_43 accept */

				/* 279 is compat_43 send */

				/* 279 is compat_43 recv */

				/* 279 is compat_43 sigvec */

				/* 279 is compat_43 sigblock */

				/* 279 is compat_43 sigsetmask */

				/* 279 is compat_43 sigstack */

				/* 279 is compat_43 recvmsg */

				/* 279 is compat_43 sendmsg */

				/* 279 is compat_43 recvfrom */

				/* 279 is compat_43 truncate */

				/* 279 is compat_43 ftruncate */

				/* 279 is compat_43 getpeername */

				/* 279 is compat_43 gethostid */

				/* 279 is compat_43 sethostid */

				/* 279 is compat_43 getrlimit */

				/* 279 is compat_43 setrlimit */

				/* 279 is compat_43 killpg */

				/* 279 is compat_43 quota */

				/* 279 is compat_43 getsockname */

				/* 279 is compat_43 getdirentries */

				/* 279 is compat_43 swapon */

				/* 279 is compat_43 obreak */

#define	SYS_MAXSYSCALL	279
