#!/bin/sh -
umask 022

if [ -f /etc/monthly.local ]; then
	echo ""
	echo "Running monthly.local:"
	. /etc/monthly.local
fi

if [ -f /var/account/acct ]; then
	echo ""
	echo "Doing login accounting:"
	ac -p | sort -nr +1
fi

if [ ! -f /etc/monthly.local -a ! -f /var/account/acct ]; then
	echo "Nothing to do!"
fi
