/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.5 2010/01/19 18:44:41 mickey Exp 
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/syscallargs.h>
#include <sys/poll.h>
#include <sys/event.h>
#include <xfs/xfs_pioctl.h>

#ifdef COMPAT_43
#define compat_43(func) __CONCAT(compat_43_,func)
#else
#define compat_43(func) sys_nosys
#endif

#ifdef COMPAT_44
#define compat_44(func) __CONCAT(compat_44_,func)
#else
#define compat_44(func) sys_nosys
#endif

#ifdef COMPAT_09
#define compat_09(func) __CONCAT(compat_09_,func)
#else
#define compat_09(func) sys_nosys
#endif

#ifdef COMPAT_10
#define compat_10(func) __CONCAT(compat_10_,func)
#else
#define compat_10(func) sys_nosys
#endif

#ifdef COMPAT_23
#define compat_23(func) __CONCAT(compat_23_,func)
#else
#define compat_23(func) sys_nosys
#endif

#ifdef COMPAT_25
#define compat_25(func) __CONCAT(compat_25_,func)
#else
#define compat_25(func) sys_nosys
#endif

#ifdef COMPAT_35
#define compat_35(func) __CONCAT(compat_35_,func)
#else
#define compat_35(func) sys_nosys
#endif

#define	s(type)	sizeof(type)

struct sysent sysent[] = {
	{ 0, 0, 0,
	    sys_nosys },			/* 0 = syscall (indir) */
	{ 0, 0, 0,
	    sys_sched_yield },			/* 1 = sched_yield */
	{ 6, s(struct sys___sysctl_args), 0,
	    sys___sysctl },			/* 2 = __sysctl */
	{ 1, s(struct sys_exit_args), 0,
	    sys_exit },				/* 3 = exit */
	{ 0, 0, 0,
	    sys_fork },				/* 4 = fork */
	{ 0, 0, 0,
	    sys_vfork },			/* 5 = vfork */
	{ 1, s(struct sys_rfork_args), 0,
	    sys_rfork },			/* 6 = rfork */
	{ 4, s(struct sys_wait4_args), 0,
	    sys_wait4 },			/* 7 = wait4 */
	{ 1, s(struct sys_fchdir_args), 0,
	    sys_fchdir },			/* 8 = fchdir */
	{ 2, s(struct sys___getcwd_args), 0,
	    sys___getcwd },			/* 9 = __getcwd */
	{ 1, s(struct sys_obreak_args), 0,
	    sys_obreak },			/* 10 = break */
	{ 0, 0, SY_NOLOCK | 0,
	    sys_getpid },			/* 11 = getpid */
	{ 4, s(struct sys_mount_args), 0,
	    sys_mount },			/* 12 = mount */
	{ 2, s(struct sys_unmount_args), 0,
	    sys_unmount },			/* 13 = unmount */
	{ 1, s(struct sys_setuid_args), 0,
	    sys_setuid },			/* 14 = setuid */
	{ 0, 0, 0,
	    sys_getuid },			/* 15 = getuid */
	{ 0, 0, 0,
	    sys_geteuid },			/* 16 = geteuid */
	{ 3, s(struct sys_recvmsg_args), 0,
	    sys_recvmsg },			/* 17 = recvmsg */
	{ 3, s(struct sys_sendmsg_args), 0,
	    sys_sendmsg },			/* 18 = sendmsg */
	{ 6, s(struct sys_recvfrom_args), 0,
	    sys_recvfrom },			/* 19 = recvfrom */
	{ 3, s(struct sys_accept_args), 0,
	    sys_accept },			/* 20 = accept */
	{ 3, s(struct sys_getpeername_args), 0,
	    sys_getpeername },			/* 21 = getpeername */
	{ 3, s(struct sys_getsockname_args), 0,
	    sys_getsockname },			/* 22 = getsockname */
	{ 2, s(struct sys_kill_args), 0,
	    sys_kill },				/* 23 = kill */
	{ 0, 0, 0,
	    sys_getppid },			/* 24 = getppid */
	{ 1, s(struct sys_dup_args), 0,
	    sys_dup },				/* 25 = dup */
	{ 0, 0, 0,
	    sys_opipe },			/* 26 = opipe */
	{ 0, 0, 0,
	    sys_getegid },			/* 27 = getegid */
	{ 4, s(struct sys_profil_args), 0,
	    sys_profil },			/* 28 = profil */
	{ 3, s(struct sys_sigaction_args), 0,
	    sys_sigaction },			/* 29 = sigaction */
	{ 0, 0, 0,
	    sys_getgid },			/* 30 = getgid */
	{ 2, s(struct sys_sigprocmask_args), 0,
	    sys_sigprocmask },			/* 31 = sigprocmask */
	{ 2, s(struct sys_getlogin_args), 0,
	    sys_getlogin },			/* 32 = getlogin */
	{ 1, s(struct sys_setlogin_args), 0,
	    sys_setlogin },			/* 33 = setlogin */
	{ 0, 0, 0,
	    sys_sigpending },			/* 34 = sigpending */
	{ 2, s(struct sys_osigaltstack_args), 0,
	    sys_osigaltstack },			/* 35 = osigaltstack */
	{ 3, s(struct sys_ioctl_args), 0,
	    sys_ioctl },			/* 36 = ioctl */
	{ 1, s(struct sys_reboot_args), 0,
	    sys_reboot },			/* 37 = reboot */
	{ 1, s(struct sys_revoke_args), 0,
	    sys_revoke },			/* 38 = revoke */
	{ 3, s(struct sys_execve_args), 0,
	    sys_execve },			/* 39 = execve */
	{ 1, s(struct sys_umask_args), 0,
	    sys_umask },			/* 40 = umask */
	{ 1, s(struct sys_chroot_args), 0,
	    sys_chroot },			/* 41 = chroot */
	{ 1, s(struct sys_sbrk_args), 0,
	    sys_sbrk },				/* 42 = sbrk */
	{ 1, s(struct sys_sstk_args), 0,
	    sys_sstk },				/* 43 = sstk */
	{ 2, s(struct sys_getgroups_args), 0,
	    sys_getgroups },			/* 44 = getgroups */
	{ 2, s(struct sys_setgroups_args), 0,
	    sys_setgroups },			/* 45 = setgroups */
	{ 0, 0, 0,
	    sys_getpgrp },			/* 46 = getpgrp */
	{ 2, s(struct sys_setpgid_args), 0,
	    sys_setpgid },			/* 47 = setpgid */
	{ 3, s(struct sys_setitimer_args), 0,
	    sys_setitimer },			/* 48 = setitimer */
	{ 2, s(struct sys_getitimer_args), 0,
	    sys_getitimer },			/* 49 = getitimer */
	{ 2, s(struct sys_dup2_args), 0,
	    sys_dup2 },				/* 50 = dup2 */
	{ 3, s(struct sys_fcntl_args), 0,
	    sys_fcntl },			/* 51 = fcntl */
	{ 3, s(struct sys_setpriority_args), 0,
	    sys_setpriority },			/* 52 = setpriority */
	{ 3, s(struct sys_socket_args), 0,
	    sys_socket },			/* 53 = socket */
	{ 3, s(struct sys_connect_args), 0,
	    sys_connect },			/* 54 = connect */
	{ 2, s(struct sys_getpriority_args), 0,
	    sys_getpriority },			/* 55 = getpriority */
	{ 1, s(struct sys_sigreturn_args), 0,
	    sys_sigreturn },			/* 56 = sigreturn */
	{ 3, s(struct sys_bind_args), 0,
	    sys_bind },				/* 57 = bind */
	{ 5, s(struct sys_setsockopt_args), 0,
	    sys_setsockopt },			/* 58 = setsockopt */
	{ 2, s(struct sys_listen_args), 0,
	    sys_listen },			/* 59 = listen */
	{ 1, s(struct sys_sigsuspend_args), 0,
	    sys_sigsuspend },			/* 60 = sigsuspend */
	{ 2, s(struct sys_gettimeofday_args), 0,
	    sys_gettimeofday },			/* 61 = gettimeofday */
	{ 2, s(struct sys_getrusage_args), 0,
	    sys_getrusage },			/* 62 = getrusage */
	{ 5, s(struct sys_getsockopt_args), 0,
	    sys_getsockopt },			/* 63 = getsockopt */
	{ 2, s(struct sys_settimeofday_args), 0,
	    sys_settimeofday },			/* 64 = settimeofday */
	{ 2, s(struct sys_setreuid_args), 0,
	    sys_setreuid },			/* 65 = setreuid */
	{ 2, s(struct sys_setregid_args), 0,
	    sys_setregid },			/* 66 = setregid */
	{ 2, s(struct sys_flock_args), 0,
	    sys_flock },			/* 67 = flock */
	{ 6, s(struct sys_sendto_args), 0,
	    sys_sendto },			/* 68 = sendto */
	{ 2, s(struct sys_shutdown_args), 0,
	    sys_shutdown },			/* 69 = shutdown */
	{ 4, s(struct sys_socketpair_args), 0,
	    sys_socketpair },			/* 70 = socketpair */
	{ 2, s(struct sys_adjtime_args), 0,
	    sys_adjtime },			/* 71 = adjtime */
	{ 0, 0, 0,
	    sys_setsid },			/* 72 = setsid */
	{ 4, s(struct sys_quotactl_args), 0,
	    sys_quotactl },			/* 73 = quotactl */
	{ 0, 0, 0,
	    sys_sync },				/* 74 = sync */
	{ 2, s(struct sys_sysarch_args), 0,
	    sys_sysarch },			/* 75 = sysarch */
	{ 1, s(struct sys_setgid_args), 0,
	    sys_setgid },			/* 76 = setgid */
	{ 1, s(struct sys_setegid_args), 0,
	    sys_setegid },			/* 77 = setegid */
	{ 1, s(struct sys_seteuid_args), 0,
	    sys_seteuid },			/* 78 = seteuid */
	{ 3, s(struct sys_mknod_args), 0,
	    sys_mknod },			/* 79 = mknod */
	{ 2, s(struct sys_mkfifo_args), 0,
	    sys_mkfifo },			/* 80 = mkfifo */
	{ 2, s(struct sys_mkdir_args), 0,
	    sys_mkdir },			/* 81 = mkdir */
	{ 1, s(struct sys_rmdir_args), 0,
	    sys_rmdir },			/* 82 = rmdir */
	{ 2, s(struct sys_symlink_args), 0,
	    sys_symlink },			/* 83 = symlink */
	{ 3, s(struct sys_readlink_args), 0,
	    sys_readlink },			/* 84 = readlink */
	{ 2, s(struct sys_rename_args), 0,
	    sys_rename },			/* 85 = rename */
	{ 2, s(struct sys_link_args), 0,
	    sys_link },				/* 86 = link */
	{ 1, s(struct sys_unlink_args), 0,
	    sys_unlink },			/* 87 = unlink */
	{ 0, 0, 0,
	    sys_nosys },			/* 88 = unimplemented sys_undelete */
	{ 2, s(struct sys_fpathconf_args), 0,
	    sys_fpathconf },			/* 89 = fpathconf */
	{ 3, s(struct sys_swapctl_args), 0,
	    sys_swapctl },			/* 90 = swapctl */
	{ 2, s(struct sys_getrlimit_args), 0,
	    sys_getrlimit },			/* 91 = getrlimit */
	{ 2, s(struct sys_setrlimit_args), 0,
	    sys_setrlimit },			/* 92 = setrlimit */
	{ 4, s(struct sys_getdirentries_args), 0,
	    sys_getdirentries },		/* 93 = getdirentries */
	{ 4, s(struct sys_lseek_args), 0,
	    sys_lseek },			/* 94 = lseek */
	{ 1, s(struct sys_getpgid_args), 0,
	    sys_getpgid },			/* 95 = getpgid */
	{ 5, s(struct sys_xfspioctl_args), 0,
	    sys_xfspioctl },			/* 96 = xfspioctl */
	{ 2, s(struct sys_clock_gettime_args), 0,
	    sys_clock_gettime },		/* 97 = clock_gettime */
	{ 2, s(struct sys_clock_settime_args), 0,
	    sys_clock_settime },		/* 98 = clock_settime */
	{ 2, s(struct sys_clock_getres_args), 0,
	    sys_clock_getres },			/* 99 = clock_getres */
	{ 0, 0, 0,
	    sys_nosys },			/* 100 = unimplemented timer_create */
	{ 0, 0, 0,
	    sys_nosys },			/* 101 = unimplemented timer_delete */
	{ 0, 0, 0,
	    sys_nosys },			/* 102 = unimplemented timer_settime */
	{ 0, 0, 0,
	    sys_nosys },			/* 103 = unimplemented timer_gettime */
	{ 0, 0, 0,
	    sys_nosys },			/* 104 = unimplemented timer_getoverrun */
	{ 7, s(struct sys_mmap_args), 0,
	    sys_mmap },				/* 105 = mmap */
	{ 2, s(struct sys_munmap_args), 0,
	    sys_munmap },			/* 106 = munmap */
	{ 3, s(struct sys_mprotect_args), 0,
	    sys_mprotect },			/* 107 = mprotect */
	{ 3, s(struct sys_madvise_args), 0,
	    sys_madvise },			/* 108 = madvise */
	{ 3, s(struct sys_mincore_args), 0,
	    sys_mincore },			/* 109 = mincore */
	{ 2, s(struct sys_mlock_args), 0,
	    sys_mlock },			/* 110 = mlock */
	{ 2, s(struct sys_munlock_args), 0,
	    sys_munlock },			/* 111 = munlock */
	{ 1, s(struct sys_mlockall_args), 0,
	    sys_mlockall },			/* 112 = mlockall */
	{ 0, 0, 0,
	    sys_munlockall },			/* 113 = munlockall */
	{ 3, s(struct sys_minherit_args), 0,
	    sys_minherit },			/* 114 = minherit */
	{ 3, s(struct sys_msync_args), 0,
	    sys_msync },			/* 115 = msync */
	{ 7, s(struct sys_mquery_args), 0,
	    sys_mquery },			/* 116 = mquery */
	{ 2, s(struct sys_nanosleep_args), 0,
	    sys_nanosleep },			/* 117 = nanosleep */
	{ 3, s(struct sys_poll_args), 0,
	    sys_poll },				/* 118 = poll */
	{ 5, s(struct sys_select_args), 0,
	    sys_select },			/* 119 = select */
	{ 0, 0, 0,
	    sys_issetugid },			/* 120 = issetugid */
	{ 1, s(struct sys_getsid_args), 0,
	    sys_getsid },			/* 121 = getsid */
	{ 1, s(struct sys_pipe_args), 0,
	    sys_pipe },				/* 122 = pipe */
	{ 0, 0, 0,
	    sys_kqueue },			/* 123 = kqueue */
	{ 6, s(struct sys_kevent_args), 0,
	    sys_kevent },			/* 124 = kevent */
	{ 3, s(struct sys_getpeereid_args), 0,
	    sys_getpeereid },			/* 125 = getpeereid */
	{ 3, s(struct sys_getresuid_args), 0,
	    sys_getresuid },			/* 126 = getresuid */
	{ 3, s(struct sys_setresuid_args), 0,
	    sys_setresuid },			/* 127 = setresuid */
	{ 3, s(struct sys_getresgid_args), 0,
	    sys_getresgid },			/* 128 = getresgid */
	{ 3, s(struct sys_setresgid_args), 0,
	    sys_setresgid },			/* 129 = setresgid */
	{ 1, s(struct sys_closefrom_args), 0,
	    sys_closefrom },			/* 130 = closefrom */
	{ 2, s(struct sys_sigaltstack_args), 0,
	    sys_sigaltstack },			/* 131 = sigaltstack */
	{ 2, s(struct sys_adjfreq_args), 0,
	    sys_adjfreq },			/* 132 = adjfreq */
	{ 3, s(struct sys_getfsstat_args), 0,
	    sys_getfsstat },			/* 133 = getfsstat */
	{ 2, s(struct sys_fstatfs_args), 0,
	    sys_fstatfs },			/* 134 = fstatfs */
	{ 2, s(struct sys_fhstatfs_args), 0,
	    sys_fhstatfs },			/* 135 = fhstatfs */
	{ 2, s(struct sys_getfh_args), 0,
	    sys_getfh },			/* 136 = getfh */
	{ 2, s(struct sys_fhopen_args), 0,
	    sys_fhopen },			/* 137 = fhopen */
	{ 2, s(struct sys_fhstat_args), 0,
	    sys_fhstat },			/* 138 = fhstat */
	{ 0, 0, 0,
	    sys_nosys },			/* 139 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 140 = unimplemented aio_open */
	{ 0, 0, 0,
	    sys_nosys },			/* 141 = unimplemented aio_read */
	{ 0, 0, 0,
	    sys_nosys },			/* 142 = unimplemented aio_write */
	{ 0, 0, 0,
	    sys_nosys },			/* 143 = unimplemented aio_fsync */
	{ 0, 0, 0,
	    sys_nosys },			/* 144 = unimplemented aio_stat */
	{ 0, 0, 0,
	    sys_nosys },			/* 145 = unimplemented aio_wstat */
	{ 0, 0, 0,
	    sys_nosys },			/* 146 = unimplemented aio_close */
	{ 0, 0, 0,
	    sys_nosys },			/* 147 = unimplemented aio_return */
	{ 0, 0, 0,
	    sys_nosys },			/* 148 = unimplemented aio_cancel */
	{ 0, 0, 0,
	    sys_nosys },			/* 149 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 150 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 151 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 152 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 153 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 154 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 155 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 156 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 157 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 158 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 159 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 160 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 161 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 162 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 163 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 164 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 165 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 166 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 167 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 168 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 169 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 170 = unimplemented sys_extattrctl */
	{ 0, 0, 0,
	    sys_nosys },			/* 171 = unimplemented sys_extattr_set_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 172 = unimplemented sys_extattr_get_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 173 = unimplemented sys_extattr_delete_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 174 = unimplemented sys_extattr_set_fd */
	{ 0, 0, 0,
	    sys_nosys },			/* 175 = unimplemented sys_extattr_get_fd */
	{ 0, 0, 0,
	    sys_nosys },			/* 176 = unimplemented sys_extattr_delete_fd */
#if defined(NFSCLIENT) || defined(NFSSERVER)
	{ 2, s(struct sys_nfssvc_args), 0,
	    sys_nfssvc },			/* 177 = nfssvc */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 177 = unimplemented */
#endif
#ifdef ACCOUNTING
	{ 1, s(struct sys_acct_args), 0,
	    sys_acct },				/* 178 = acct */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 178 = unimplemented acct */
#endif
#ifdef PTRACE
	{ 4, s(struct sys_ptrace_args), 0,
	    sys_ptrace },			/* 179 = ptrace */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 179 = unimplemented ptrace */
#endif
#ifdef KTRACE
	{ 4, s(struct sys_ktrace_args), 0,
	    sys_ktrace },			/* 180 = ktrace */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 180 = unimplemented ktrace */
#endif
#ifdef SYSVSEM
	{ 3, s(struct sys_semget_args), 0,
	    sys_semget },			/* 181 = semget */
	{ 3, s(struct sys_semop_args), 0,
	    sys_semop },			/* 182 = semop */
	{ 4, s(struct sys___semctl_args), 0,
	    sys___semctl },			/* 183 = __semctl */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 181 = unimplemented semget */
	{ 0, 0, 0,
	    sys_nosys },			/* 182 = unimplemented semop */
	{ 0, 0, 0,
	    sys_nosys },			/* 183 = unimplemented ___semctl */
#endif
#ifdef SYSVSHM
	{ 3, s(struct sys_shmget_args), 0,
	    sys_shmget },			/* 184 = shmget */
	{ 3, s(struct sys_shmctl_args), 0,
	    sys_shmctl },			/* 185 = shmctl */
	{ 3, s(struct sys_shmat_args), 0,
	    sys_shmat },			/* 186 = shmat */
	{ 1, s(struct sys_shmdt_args), 0,
	    sys_shmdt },			/* 187 = shmdt */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 184 = unimplemented shmget */
	{ 0, 0, 0,
	    sys_nosys },			/* 185 = unimplemented shmctl */
	{ 0, 0, 0,
	    sys_nosys },			/* 186 = unimplemented shmat */
	{ 0, 0, 0,
	    sys_nosys },			/* 187 = unimplemented shmdt */
#endif
#ifdef SYSVMSG
	{ 2, s(struct sys_msgget_args), 0,
	    sys_msgget },			/* 188 = msgget */
	{ 4, s(struct sys_msgsnd_args), 0,
	    sys_msgsnd },			/* 189 = msgsnd */
	{ 5, s(struct sys_msgrcv_args), 0,
	    sys_msgrcv },			/* 190 = msgrcv */
	{ 3, s(struct sys_msgctl_args), 0,
	    sys_msgctl },			/* 191 = msgctl */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 188 = unimplemented msgget */
	{ 0, 0, 0,
	    sys_nosys },			/* 189 = unimplemented msgsnd */
	{ 0, 0, 0,
	    sys_nosys },			/* 190 = unimplemented msgrcv */
	{ 0, 0, 0,
	    sys_nosys },			/* 191 = unimplemented msgctl */
#endif
#ifdef RTHREADS
	{ 0, 0, 0,
	    sys_getthrid },			/* 192 = getthrid */
	{ 3, s(struct sys_thrsleep_args), 0,
	    sys_thrsleep },			/* 193 = thrsleep */
	{ 2, s(struct sys_thrwakeup_args), 0,
	    sys_thrwakeup },			/* 194 = thrwakeup */
	{ 1, s(struct sys_threxit_args), 0,
	    sys_threxit },			/* 195 = threxit */
	{ 1, s(struct sys_thrsigdivert_args), 0,
	    sys_thrsigdivert },			/* 196 = thrsigdivert */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 192 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 193 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 194 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 195 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 196 = unimplemented */
#endif
	{ 0, 0, 0,
	    sys_nosys },			/* 197 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 198 = __syscall (indir) */
	{ 0, 0, 0,
	    sys_nosys },			/* 199 = unimplemented */
#ifdef LKM
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 200 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 201 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 202 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 203 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 204 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 205 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 206 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 207 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 208 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 209 = lkmnosys */
#else	/* !LKM */
	{ 0, 0, 0,
	    sys_nosys },			/* 200 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 201 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 202 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 203 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 204 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 205 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 206 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 207 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 208 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 209 = unimplemented */
#endif	/* !LKM */
	{ 0, 0, 0,
	    sys_nosys },			/* 210 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 211 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 212 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 213 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 214 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 215 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 216 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 217 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 218 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 219 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 220 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 221 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 222 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 223 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 224 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 225 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 226 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 227 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 228 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 229 = unimplemented */
	{ 3, s(struct sys_open_args), 0,
	    sys_open },				/* 230 = open */
	{ 3, s(struct sys_read_args), 0,
	    sys_read },				/* 231 = read */
	{ 3, s(struct sys_write_args), 0,
	    sys_write },			/* 232 = write */
	{ 3, s(struct sys_readv_args), 0,
	    sys_readv },			/* 233 = readv */
	{ 3, s(struct sys_writev_args), 0,
	    sys_writev },			/* 234 = writev */
	{ 5, s(struct sys_pread_args), 0,
	    sys_pread },			/* 235 = pread */
	{ 5, s(struct sys_pwrite_args), 0,
	    sys_pwrite },			/* 236 = pwrite */
	{ 5, s(struct sys_preadv_args), 0,
	    sys_preadv },			/* 237 = preadv */
	{ 5, s(struct sys_pwritev_args), 0,
	    sys_pwritev },			/* 238 = pwritev */
	{ 1, s(struct sys_fsync_args), 0,
	    sys_fsync },			/* 239 = fsync */
	{ 2, s(struct sys_fstat_args), 0,
	    sys_fstat },			/* 240 = fstat */
	{ 3, s(struct sys_ftruncate_args), 0,
	    sys_ftruncate },			/* 241 = ftruncate */
	{ 2, s(struct sys_futimes_args), 0,
	    sys_futimes },			/* 242 = futimes */
	{ 2, s(struct sys_fchmod_args), 0,
	    sys_fchmod },			/* 243 = fchmod */
	{ 3, s(struct sys_fchown_args), 0,
	    sys_fchown },			/* 244 = fchown */
	{ 2, s(struct sys_fchflags_args), 0,
	    sys_fchflags },			/* 245 = fchflags */
	{ 1, s(struct sys_close_args), 0,
	    sys_close },			/* 246 = close */
	{ 1, s(struct sys_chdir_args), 0,
	    sys_chdir },			/* 247 = chdir */
	{ 2, s(struct sys_pathconf_args), 0,
	    sys_pathconf },			/* 248 = pathconf */
	{ 2, s(struct sys_access_args), 0,
	    sys_access },			/* 249 = access */
	{ 2, s(struct sys_stat_args), 0,
	    sys_stat },				/* 250 = stat */
	{ 2, s(struct sys_lstat_args), 0,
	    sys_lstat },			/* 251 = lstat */
	{ 2, s(struct sys_statfs_args), 0,
	    sys_statfs },			/* 252 = statfs */
	{ 3, s(struct sys_truncate_args), 0,
	    sys_truncate },			/* 253 = truncate */
	{ 2, s(struct sys_utimes_args), 0,
	    sys_utimes },			/* 254 = utimes */
	{ 2, s(struct sys_chmod_args), 0,
	    sys_chmod },			/* 255 = chmod */
	{ 3, s(struct sys_chown_args), 0,
	    sys_chown },			/* 256 = chown */
	{ 3, s(struct sys_lchown_args), 0,
	    sys_lchown },			/* 257 = lchown */
	{ 2, s(struct sys_chflags_args), 0,
	    sys_chflags },			/* 258 = chflags */
};

