/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.7 2010/02/15 09:42:19 mickey Exp 
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/syscallargs.h>
#include <sys/poll.h>
#include <sys/event.h>
#include <xfs/xfs_pioctl.h>

#ifdef COMPAT_43
#define compat_43(func) __CONCAT(compat_43_,func)
#else
#define compat_43(func) sys_nosys
#endif

#ifdef COMPAT_44
#define compat_44(func) __CONCAT(compat_44_,func)
#else
#define compat_44(func) sys_nosys
#endif

#define	s(type)	sizeof(type)

struct sysent sysent[] = {
	{ 0, 0, 0,
	    sys_nosys },			/* 0 = syscall (indir) */
	{ 0, 0, 0,
	    sys_sched_yield },			/* 1 = sched_yield */
	{ 6, s(struct sys___sysctl_args), 0,
	    sys___sysctl },			/* 2 = __sysctl */
	{ 1, s(struct sys_exit_args), 0,
	    sys_exit },				/* 3 = exit */
	{ 0, 0, 0,
	    sys_fork },				/* 4 = fork */
	{ 0, 0, 0,
	    sys_vfork },			/* 5 = vfork */
	{ 1, s(struct sys_rfork_args), 0,
	    sys_rfork },			/* 6 = rfork */
	{ 4, s(struct sys_wait4_args), 0,
	    sys_wait4 },			/* 7 = wait4 */
	{ 1, s(struct sys_fchdir_args), 0,
	    sys_fchdir },			/* 8 = fchdir */
	{ 2, s(struct sys___getcwd_args), 0,
	    sys___getcwd },			/* 9 = __getcwd */
	{ 1, s(struct sys_closefrom_args), 0,
	    sys_closefrom },			/* 10 = closefrom */
	{ 0, 0, 0,
	    sys_nosys },			/* 11 = unimplemented { int sys_pstat ( int which , id_t who , struct kinfo_proc * kip , size_t * len ) ; } */
	{ 4, s(struct sys_mount_args), 0,
	    sys_mount },			/* 12 = mount */
	{ 2, s(struct sys_unmount_args), 0,
	    sys_unmount },			/* 13 = unmount */
	{ 1, s(struct sys_setuid_args), 0,
	    sys_setuid },			/* 14 = setuid */
	{ 1, s(struct sys_getpgid_args), 0,
	    sys_getpgid },			/* 15 = getpgid */
	{ 7, s(struct sys_mmap_args), 0,
	    sys_mmap },				/* 16 = mmap */
	{ 2, s(struct sys_munmap_args), 0,
	    sys_munmap },			/* 17 = munmap */
	{ 3, s(struct sys_mprotect_args), 0,
	    sys_mprotect },			/* 18 = mprotect */
	{ 3, s(struct sys_madvise_args), 0,
	    sys_madvise },			/* 19 = madvise */
	{ 3, s(struct sys_mincore_args), 0,
	    sys_mincore },			/* 20 = mincore */
	{ 2, s(struct sys_mlock_args), 0,
	    sys_mlock },			/* 21 = mlock */
	{ 2, s(struct sys_munlock_args), 0,
	    sys_munlock },			/* 22 = munlock */
	{ 1, s(struct sys_mlockall_args), 0,
	    sys_mlockall },			/* 23 = mlockall */
	{ 0, 0, 0,
	    sys_munlockall },			/* 24 = munlockall */
	{ 3, s(struct sys_minherit_args), 0,
	    sys_minherit },			/* 25 = minherit */
	{ 3, s(struct sys_msync_args), 0,
	    sys_msync },			/* 26 = msync */
	{ 7, s(struct sys_mquery_args), 0,
	    sys_mquery },			/* 27 = mquery */
	{ 1, s(struct sys_chroot_args), 0,
	    sys_chroot },			/* 28 = chroot */
	{ 1, s(struct sys_umask_args), 0,
	    sys_umask },			/* 29 = umask */
	{ 3, s(struct sys_execve_args), 0,
	    sys_execve },			/* 30 = execve */
	{ 2, s(struct sys_kill_args), 0,
	    sys_kill },				/* 31 = kill */
	{ 4, s(struct sys_profil_args), 0,
	    sys_profil },			/* 32 = profil */
	{ 3, s(struct sys_sigaction_args), 0,
	    sys_sigaction },			/* 33 = sigaction */
	{ 2, s(struct sys_sigprocmask_args), 0,
	    sys_sigprocmask },			/* 34 = sigprocmask */
	{ 2, s(struct sys_nanosleep_args), 0,
	    sys_nanosleep },			/* 35 = nanosleep */
	{ 3, s(struct sys_poll_args), 0,
	    sys_poll },				/* 36 = poll */
	{ 5, s(struct sys_select_args), 0,
	    sys_select },			/* 37 = select */
	{ 1, s(struct sys_setlogin_args), 0,
	    sys_setlogin },			/* 38 = setlogin */
	{ 2, s(struct sys_sigaltstack_args), 0,
	    sys_sigaltstack },			/* 39 = sigaltstack */
	{ 3, s(struct sys_ioctl_args), 0,
	    sys_ioctl },			/* 40 = ioctl */
	{ 1, s(struct sys_reboot_args), 0,
	    sys_reboot },			/* 41 = reboot */
	{ 1, s(struct sys_revoke_args), 0,
	    sys_revoke },			/* 42 = revoke */
	{ 3, s(struct sys_setpriority_args), 0,
	    sys_setpriority },			/* 43 = setpriority */
	{ 2, s(struct sys_getpriority_args), 0,
	    sys_getpriority },			/* 44 = getpriority */
	{ 1, s(struct sys_sigreturn_args), 0,
	    sys_sigreturn },			/* 45 = sigreturn */
	{ 2, s(struct sys_adjfreq_args), 0,
	    sys_adjfreq },			/* 46 = adjfreq */
	{ 2, s(struct sys_adjtime_args), 0,
	    sys_adjtime },			/* 47 = adjtime */
	{ 2, s(struct sys_gettimeofday_args), 0,
	    sys_gettimeofday },			/* 48 = gettimeofday */
	{ 1, s(struct sys_sigsuspend_args), 0,
	    sys_sigsuspend },			/* 49 = sigsuspend */
	{ 2, s(struct sys_setgroups_args), 0,
	    sys_setgroups },			/* 50 = setgroups */
	{ 2, s(struct sys_setpgid_args), 0,
	    sys_setpgid },			/* 51 = setpgid */
	{ 3, s(struct sys_setitimer_args), 0,
	    sys_setitimer },			/* 52 = setitimer */
	{ 2, s(struct sys_getitimer_args), 0,
	    sys_getitimer },			/* 53 = getitimer */
	{ 2, s(struct sys_settimeofday_args), 0,
	    sys_settimeofday },			/* 54 = settimeofday */
	{ 2, s(struct sys_setreuid_args), 0,
	    sys_setreuid },			/* 55 = setreuid */
	{ 2, s(struct sys_setregid_args), 0,
	    sys_setregid },			/* 56 = setregid */
	{ 6, s(struct sys_sendto_args), 0,
	    sys_sendto },			/* 57 = sendto */
	{ 0, 0, 0,
	    sys_setsid },			/* 58 = setsid */
	{ 4, s(struct sys_quotactl_args), 0,
	    sys_quotactl },			/* 59 = quotactl */
	{ 0, 0, 0,
	    sys_nosys },			/* 60 = unimplemented aio_open */
	{ 0, 0, 0,
	    sys_nosys },			/* 61 = unimplemented aio_read */
	{ 0, 0, 0,
	    sys_nosys },			/* 62 = unimplemented aio_write */
	{ 0, 0, 0,
	    sys_nosys },			/* 63 = unimplemented aio_fsync */
	{ 0, 0, 0,
	    sys_nosys },			/* 64 = unimplemented aio_stat */
	{ 0, 0, 0,
	    sys_nosys },			/* 65 = unimplemented aio_wstat */
	{ 0, 0, 0,
	    sys_nosys },			/* 66 = unimplemented aio_close */
	{ 0, 0, 0,
	    sys_nosys },			/* 67 = unimplemented aio_return */
	{ 0, 0, 0,
	    sys_nosys },			/* 68 = unimplemented aio_cancel */
	{ 0, 0, 0,
	    sys_nosys },			/* 69 = unimplemented */
	{ 0, 0, 0,
	    sys_sync },				/* 70 = sync */
	{ 2, s(struct sys_sysarch_args), 0,
	    sys_sysarch },			/* 71 = sysarch */
	{ 1, s(struct sys_setgid_args), 0,
	    sys_setgid },			/* 72 = setgid */
	{ 1, s(struct sys_setegid_args), 0,
	    sys_setegid },			/* 73 = setegid */
	{ 1, s(struct sys_seteuid_args), 0,
	    sys_seteuid },			/* 74 = seteuid */
	{ 3, s(struct sys_setresuid_args), 0,
	    sys_setresuid },			/* 75 = setresuid */
	{ 3, s(struct sys_setresgid_args), 0,
	    sys_setresgid },			/* 76 = setresgid */
	{ 3, s(struct sys_getfsstat_args), 0,
	    sys_getfsstat },			/* 77 = getfsstat */
	{ 1, s(struct sys_rmdir_args), 0,
	    sys_rmdir },			/* 78 = rmdir */
	{ 2, s(struct sys_rename_args), 0,
	    sys_rename },			/* 79 = rename */
	{ 1, s(struct sys_unlink_args), 0,
	    sys_unlink },			/* 80 = unlink */
	{ 0, 0, 0,
	    sys_nosys },			/* 81 = unimplemented sys_undelete */
	{ 3, s(struct sys_swapctl_args), 0,
	    sys_swapctl },			/* 82 = swapctl */
	{ 2, s(struct sys_setrlimit_args), 0,
	    sys_setrlimit },			/* 83 = setrlimit */
	{ 4, s(struct sys_getdirentries_args), 0,
	    sys_getdirentries },		/* 84 = getdirentries */
	{ 2, s(struct sys_clock_gettime_args), 0,
	    sys_clock_gettime },		/* 85 = clock_gettime */
	{ 2, s(struct sys_clock_settime_args), 0,
	    sys_clock_settime },		/* 86 = clock_settime */
	{ 2, s(struct sys_clock_getres_args), 0,
	    sys_clock_getres },			/* 87 = clock_getres */
	{ 0, 0, 0,
	    sys_nosys },			/* 88 = unimplemented timer_create */
	{ 0, 0, 0,
	    sys_nosys },			/* 89 = unimplemented timer_delete */
	{ 0, 0, 0,
	    sys_nosys },			/* 90 = unimplemented timer_settime */
	{ 0, 0, 0,
	    sys_nosys },			/* 91 = unimplemented timer_gettime */
	{ 0, 0, 0,
	    sys_nosys },			/* 92 = unimplemented timer_getoverrun */
	{ 0, 0, 0,
	    sys_nosys },			/* 93 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 94 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 95 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 96 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 97 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 98 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 99 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 100 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 101 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 102 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 103 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 104 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 105 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 106 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 107 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 108 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 109 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 110 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 111 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 112 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 113 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 114 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 115 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 116 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 117 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 118 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 119 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 120 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 121 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 122 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 123 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 124 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 125 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 126 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 127 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 128 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 129 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 130 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 131 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 132 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 133 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 134 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 135 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 136 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 137 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 138 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 139 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 140 = unimplemented sys_extattrctl */
	{ 0, 0, 0,
	    sys_nosys },			/* 141 = unimplemented sys_extattr_set_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 142 = unimplemented sys_extattr_get_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 143 = unimplemented sys_extattr_delete_file */
	{ 0, 0, 0,
	    sys_nosys },			/* 144 = unimplemented sys_extattr_set_fd */
	{ 0, 0, 0,
	    sys_nosys },			/* 145 = unimplemented sys_extattr_get_fd */
	{ 0, 0, 0,
	    sys_nosys },			/* 146 = unimplemented sys_extattr_delete_fd */
#ifdef XFS
	{ 5, s(struct sys_xfspioctl_args), 0,
	    sys_xfspioctl },			/* 147 = xfspioctl */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 147 = unimplemented xfspioctl */
#endif
#if defined(NFSCLIENT) || defined(NFSSERVER)
	{ 2, s(struct sys_nfssvc_args), 0,
	    sys_nfssvc },			/* 148 = nfssvc */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 148 = unimplemented nfssvc */
#endif
#ifdef ACCOUNTING
	{ 1, s(struct sys_acct_args), 0,
	    sys_acct },				/* 149 = acct */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 149 = unimplemented acct */
#endif
#ifdef PTRACE
	{ 4, s(struct sys_ptrace_args), 0,
	    sys_ptrace },			/* 150 = ptrace */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 150 = unimplemented ptrace */
#endif
#ifdef KTRACE
	{ 4, s(struct sys_ktrace_args), 0,
	    sys_ktrace },			/* 151 = ktrace */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 151 = unimplemented ktrace */
#endif
#ifdef SYSVSEM
	{ 3, s(struct sys_semget_args), 0,
	    sys_semget },			/* 152 = semget */
	{ 3, s(struct sys_semop_args), 0,
	    sys_semop },			/* 153 = semop */
	{ 4, s(struct sys___semctl_args), 0,
	    sys___semctl },			/* 154 = __semctl */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 152 = unimplemented semget */
	{ 0, 0, 0,
	    sys_nosys },			/* 153 = unimplemented semop */
	{ 0, 0, 0,
	    sys_nosys },			/* 154 = unimplemented ___semctl */
#endif
#ifdef SYSVSHM
	{ 3, s(struct sys_shmget_args), 0,
	    sys_shmget },			/* 155 = shmget */
	{ 3, s(struct sys_shmctl_args), 0,
	    sys_shmctl },			/* 156 = shmctl */
	{ 3, s(struct sys_shmat_args), 0,
	    sys_shmat },			/* 157 = shmat */
	{ 1, s(struct sys_shmdt_args), 0,
	    sys_shmdt },			/* 158 = shmdt */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 155 = unimplemented shmget */
	{ 0, 0, 0,
	    sys_nosys },			/* 156 = unimplemented shmctl */
	{ 0, 0, 0,
	    sys_nosys },			/* 157 = unimplemented shmat */
	{ 0, 0, 0,
	    sys_nosys },			/* 158 = unimplemented shmdt */
#endif
#ifdef SYSVMSG
	{ 2, s(struct sys_msgget_args), 0,
	    sys_msgget },			/* 159 = msgget */
	{ 4, s(struct sys_msgsnd_args), 0,
	    sys_msgsnd },			/* 160 = msgsnd */
	{ 5, s(struct sys_msgrcv_args), 0,
	    sys_msgrcv },			/* 161 = msgrcv */
	{ 3, s(struct sys_msgctl_args), 0,
	    sys_msgctl },			/* 162 = msgctl */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 159 = unimplemented msgget */
	{ 0, 0, 0,
	    sys_nosys },			/* 160 = unimplemented msgsnd */
	{ 0, 0, 0,
	    sys_nosys },			/* 161 = unimplemented msgrcv */
	{ 0, 0, 0,
	    sys_nosys },			/* 162 = unimplemented msgctl */
#endif
#ifdef RTHREADS
	{ 0, 0, 0,
	    sys_getthrid },			/* 163 = getthrid */
	{ 3, s(struct sys_thrsleep_args), 0,
	    sys_thrsleep },			/* 164 = thrsleep */
	{ 2, s(struct sys_thrwakeup_args), 0,
	    sys_thrwakeup },			/* 165 = thrwakeup */
	{ 1, s(struct sys_threxit_args), 0,
	    sys_threxit },			/* 166 = threxit */
	{ 1, s(struct sys_thrsigdivert_args), 0,
	    sys_thrsigdivert },			/* 167 = thrsigdivert */
#else
	{ 0, 0, 0,
	    sys_nosys },			/* 163 = unimplemented getthrid */
	{ 0, 0, 0,
	    sys_nosys },			/* 164 = unimplemented thrsleep */
	{ 0, 0, 0,
	    sys_nosys },			/* 165 = unimplemented thrwakeup */
	{ 0, 0, 0,
	    sys_nosys },			/* 166 = unimplemented threxit */
	{ 0, 0, 0,
	    sys_nosys },			/* 167 = unimplemented thrsigdivert */
#endif
	{ 0, 0, 0,
	    sys_nosys },			/* 168 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 169 = unimplemented */
#ifdef LKM
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 170 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 171 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 172 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 173 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 174 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 175 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 176 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 177 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 178 = lkmnosys */
	{ 0, 0, 0,
	    sys_lkmnosys },			/* 179 = lkmnosys */
#else	/* !LKM */
	{ 0, 0, 0,
	    sys_nosys },			/* 170 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 171 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 172 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 173 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 174 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 175 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 176 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 177 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 178 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 179 = unimplemented */
#endif	/* !LKM */
	{ 0, 0, 0,
	    sys_nosys },			/* 180 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 181 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 182 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 183 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 184 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 185 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 186 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 187 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 188 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 189 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 190 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 191 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 192 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 193 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 194 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 195 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 196 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 197 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys },			/* 198 = __syscall (indir) */
	{ 3, s(struct sys_getpeereid_args), 0,
	    sys_getpeereid },			/* 199 = getpeereid */
	{ 5, s(struct sys_setsockopt_args), 0,
	    sys_setsockopt },			/* 200 = setsockopt */
	{ 5, s(struct sys_getsockopt_args), 0,
	    sys_getsockopt },			/* 201 = getsockopt */
	{ 3, s(struct sys_getpeername_args), 0,
	    sys_getpeername },			/* 202 = getpeername */
	{ 3, s(struct sys_getsockname_args), 0,
	    sys_getsockname },			/* 203 = getsockname */
	{ 2, s(struct sys_access_args), 0,
	    sys_access },			/* 204 = access */
	{ 3, s(struct sys_accept_args), 0,
	    sys_accept },			/* 205 = accept */
	{ 2, s(struct sys_listen_args), 0,
	    sys_listen },			/* 206 = listen */
	{ 3, s(struct sys_connect_args), 0,
	    sys_connect },			/* 207 = connect */
	{ 3, s(struct sys_bind_args), 0,
	    sys_bind },				/* 208 = bind */
	{ 2, s(struct sys_fstatfs_args), 0,
	    sys_fstatfs },			/* 209 = fstatfs */
	{ 0, 0, 0,
	    sys_kqueue },			/* 210 = kqueue */
	{ 6, s(struct sys_kevent_args), 0,
	    sys_kevent },			/* 211 = kevent */
	{ 1, s(struct sys_pipe_args), 0,
	    sys_pipe },				/* 212 = pipe */
	{ 4, s(struct sys_socketpair_args), 0,
	    sys_socketpair },			/* 213 = socketpair */
	{ 3, s(struct sys_socket_args), 0,
	    sys_socket },			/* 214 = socket */
	{ 2, s(struct sys_link_args), 0,
	    sys_link },				/* 215 = link */
	{ 2, s(struct sys_symlink_args), 0,
	    sys_symlink },			/* 216 = symlink */
	{ 3, s(struct sys_readlink_args), 0,
	    sys_readlink },			/* 217 = readlink */
	{ 2, s(struct sys_mkfifo_args), 0,
	    sys_mkfifo },			/* 218 = mkfifo */
	{ 2, s(struct sys_mkdir_args), 0,
	    sys_mkdir },			/* 219 = mkdir */
	{ 3, s(struct sys_mknod_args), 0,
	    sys_mknod },			/* 220 = mknod */
	{ 2, s(struct sys_fhstatfs_args), 0,
	    sys_fhstatfs },			/* 221 = fhstatfs */
	{ 2, s(struct sys_getfh_args), 0,
	    sys_getfh },			/* 222 = getfh */
	{ 2, s(struct sys_fhopen_args), 0,
	    sys_fhopen },			/* 223 = fhopen */
	{ 2, s(struct sys_fhstat_args), 0,
	    sys_fhstat },			/* 224 = fhstat */
	{ 3, s(struct sys_recvmsg_args), 0,
	    sys_recvmsg },			/* 225 = recvmsg */
	{ 3, s(struct sys_sendmsg_args), 0,
	    sys_sendmsg },			/* 226 = sendmsg */
	{ 6, s(struct sys_recvfrom_args), 0,
	    sys_recvfrom },			/* 227 = recvfrom */
	{ 3, s(struct sys_open_args), 0,
	    sys_open },				/* 228 = open */
	{ 3, s(struct sys_read_args), 0,
	    sys_read },				/* 229 = read */
	{ 3, s(struct sys_write_args), 0,
	    sys_write },			/* 230 = write */
	{ 3, s(struct sys_readv_args), 0,
	    sys_readv },			/* 231 = readv */
	{ 3, s(struct sys_writev_args), 0,
	    sys_writev },			/* 232 = writev */
	{ 5, s(struct sys_pread_args), 0,
	    sys_pread },			/* 233 = pread */
	{ 5, s(struct sys_pwrite_args), 0,
	    sys_pwrite },			/* 234 = pwrite */
	{ 5, s(struct sys_preadv_args), 0,
	    sys_preadv },			/* 235 = preadv */
	{ 5, s(struct sys_pwritev_args), 0,
	    sys_pwritev },			/* 236 = pwritev */
	{ 1, s(struct sys_fsync_args), 0,
	    sys_fsync },			/* 237 = fsync */
	{ 2, s(struct sys_fstat_args), 0,
	    sys_fstat },			/* 238 = fstat */
	{ 3, s(struct sys_ftruncate_args), 0,
	    sys_ftruncate },			/* 239 = ftruncate */
	{ 2, s(struct sys_futimes_args), 0,
	    sys_futimes },			/* 240 = futimes */
	{ 2, s(struct sys_fchmod_args), 0,
	    sys_fchmod },			/* 241 = fchmod */
	{ 3, s(struct sys_fchown_args), 0,
	    sys_fchown },			/* 242 = fchown */
	{ 2, s(struct sys_fchflags_args), 0,
	    sys_fchflags },			/* 243 = fchflags */
	{ 1, s(struct sys_close_args), 0,
	    sys_close },			/* 244 = close */
	{ 1, s(struct sys_chdir_args), 0,
	    sys_chdir },			/* 245 = chdir */
	{ 2, s(struct sys_pathconf_args), 0,
	    sys_pathconf },			/* 246 = pathconf */
	{ 2, s(struct sys_stat_args), 0,
	    sys_stat },				/* 247 = stat */
	{ 2, s(struct sys_lstat_args), 0,
	    sys_lstat },			/* 248 = lstat */
	{ 2, s(struct sys_statfs_args), 0,
	    sys_statfs },			/* 249 = statfs */
	{ 3, s(struct sys_truncate_args), 0,
	    sys_truncate },			/* 250 = truncate */
	{ 2, s(struct sys_utimes_args), 0,
	    sys_utimes },			/* 251 = utimes */
	{ 2, s(struct sys_chmod_args), 0,
	    sys_chmod },			/* 252 = chmod */
	{ 3, s(struct sys_chown_args), 0,
	    sys_chown },			/* 253 = chown */
	{ 3, s(struct sys_lchown_args), 0,
	    sys_lchown },			/* 254 = lchown */
	{ 2, s(struct sys_chflags_args), 0,
	    sys_chflags },			/* 255 = chflags */
	{ 3, s(struct sys_fcntl_args), 0,
	    sys_fcntl },			/* 256 = fcntl */
	{ 1, s(struct sys_dup_args), 0,
	    sys_dup },				/* 257 = dup */
	{ 2, s(struct sys_dup2_args), 0,
	    sys_dup2 },				/* 258 = dup2 */
	{ 2, s(struct sys_flock_args), 0,
	    sys_flock },			/* 259 = flock */
	{ 2, s(struct sys_fpathconf_args), 0,
	    sys_fpathconf },			/* 260 = fpathconf */
	{ 4, s(struct sys_lseek_args), 0,
	    sys_lseek },			/* 261 = lseek */
	{ 2, s(struct sys_shutdown_args), 0,
	    sys_shutdown },			/* 262 = shutdown */
	{ 0, 0, SY_NOLOCK | 0,
	    sys_getpid },			/* 263 = getpid */
	{ 0, 0, 0,
	    sys_getuid },			/* 264 = getuid */
	{ 0, 0, 0,
	    sys_geteuid },			/* 265 = geteuid */
	{ 0, 0, 0,
	    sys_getppid },			/* 266 = getppid */
	{ 0, 0, 0,
	    sys_getegid },			/* 267 = getegid */
	{ 0, 0, 0,
	    sys_getgid },			/* 268 = getgid */
	{ 2, s(struct sys_getlogin_args), 0,
	    sys_getlogin },			/* 269 = getlogin */
	{ 0, 0, 0,
	    sys_sigpending },			/* 270 = sigpending */
	{ 0, 0, 0,
	    sys_issetugid },			/* 271 = issetugid */
	{ 2, s(struct sys_getgroups_args), 0,
	    sys_getgroups },			/* 272 = getgroups */
	{ 0, 0, 0,
	    sys_getpgrp },			/* 273 = getpgrp */
	{ 2, s(struct sys_getrusage_args), 0,
	    sys_getrusage },			/* 274 = getrusage */
	{ 1, s(struct sys_getsid_args), 0,
	    sys_getsid },			/* 275 = getsid */
	{ 2, s(struct sys_getrlimit_args), 0,
	    sys_getrlimit },			/* 276 = getrlimit */
	{ 3, s(struct sys_getresuid_args), 0,
	    sys_getresuid },			/* 277 = getresuid */
	{ 3, s(struct sys_getresgid_args), 0,
	    sys_getresgid },			/* 278 = getresgid */
};

