/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.6 2010/02/12 14:25:06 mickey Exp 
 */

const char *syscallnames[] = {
	"syscall",			/* 0 = syscall */
	"sched_yield",			/* 1 = sched_yield */
	"__sysctl",			/* 2 = __sysctl */
	"exit",			/* 3 = exit */
	"fork",			/* 4 = fork */
	"vfork",			/* 5 = vfork */
	"rfork",			/* 6 = rfork */
	"wait4",			/* 7 = wait4 */
	"fchdir",			/* 8 = fchdir */
	"__getcwd",			/* 9 = __getcwd */
	"closefrom",			/* 10 = closefrom */
	"getpid",			/* 11 = getpid */
	"mount",			/* 12 = mount */
	"unmount",			/* 13 = unmount */
	"setuid",			/* 14 = setuid */
	"getuid",			/* 15 = getuid */
	"geteuid",			/* 16 = geteuid */
	"recvmsg",			/* 17 = recvmsg */
	"sendmsg",			/* 18 = sendmsg */
	"recvfrom",			/* 19 = recvfrom */
	"accept",			/* 20 = accept */
	"getpeername",			/* 21 = getpeername */
	"getsockname",			/* 22 = getsockname */
	"kill",			/* 23 = kill */
	"getppid",			/* 24 = getppid */
	"dup",			/* 25 = dup */
	"getegid",			/* 26 = getegid */
	"profil",			/* 27 = profil */
	"sigaction",			/* 28 = sigaction */
	"getgid",			/* 29 = getgid */
	"sigprocmask",			/* 30 = sigprocmask */
	"getlogin",			/* 31 = getlogin */
	"setlogin",			/* 32 = setlogin */
	"sigpending",			/* 33 = sigpending */
	"sigaltstack",			/* 34 = sigaltstack */
	"ioctl",			/* 35 = ioctl */
	"reboot",			/* 36 = reboot */
	"revoke",			/* 37 = revoke */
	"execve",			/* 38 = execve */
	"umask",			/* 39 = umask */
	"chroot",			/* 40 = chroot */
	"issetugid",			/* 41 = issetugid */
	"adjfreq",			/* 42 = adjfreq */
	"adjtime",			/* 43 = adjtime */
	"getgroups",			/* 44 = getgroups */
	"setgroups",			/* 45 = setgroups */
	"getpgrp",			/* 46 = getpgrp */
	"setpgid",			/* 47 = setpgid */
	"setitimer",			/* 48 = setitimer */
	"getitimer",			/* 49 = getitimer */
	"dup2",			/* 50 = dup2 */
	"getpeereid",			/* 51 = getpeereid */
	"setpriority",			/* 52 = setpriority */
	"socket",			/* 53 = socket */
	"connect",			/* 54 = connect */
	"getpriority",			/* 55 = getpriority */
	"sigreturn",			/* 56 = sigreturn */
	"bind",			/* 57 = bind */
	"setsockopt",			/* 58 = setsockopt */
	"listen",			/* 59 = listen */
	"sigsuspend",			/* 60 = sigsuspend */
	"gettimeofday",			/* 61 = gettimeofday */
	"getrusage",			/* 62 = getrusage */
	"getsockopt",			/* 63 = getsockopt */
	"settimeofday",			/* 64 = settimeofday */
	"setreuid",			/* 65 = setreuid */
	"setregid",			/* 66 = setregid */
	"flock",			/* 67 = flock */
	"sendto",			/* 68 = sendto */
	"shutdown",			/* 69 = shutdown */
	"socketpair",			/* 70 = socketpair */
	"getsid",			/* 71 = getsid */
	"setsid",			/* 72 = setsid */
	"quotactl",			/* 73 = quotactl */
	"sync",			/* 74 = sync */
	"sysarch",			/* 75 = sysarch */
	"setgid",			/* 76 = setgid */
	"setegid",			/* 77 = setegid */
	"seteuid",			/* 78 = seteuid */
	"mknod",			/* 79 = mknod */
	"mkfifo",			/* 80 = mkfifo */
	"mkdir",			/* 81 = mkdir */
	"rmdir",			/* 82 = rmdir */
	"symlink",			/* 83 = symlink */
	"readlink",			/* 84 = readlink */
	"rename",			/* 85 = rename */
	"link",			/* 86 = link */
	"unlink",			/* 87 = unlink */
	"#88 (unimplemented sys_undelete)",		/* 88 = unimplemented sys_undelete */
	"fpathconf",			/* 89 = fpathconf */
	"swapctl",			/* 90 = swapctl */
	"getrlimit",			/* 91 = getrlimit */
	"setrlimit",			/* 92 = setrlimit */
	"getdirentries",			/* 93 = getdirentries */
	"lseek",			/* 94 = lseek */
	"getpgid",			/* 95 = getpgid */
	"xfspioctl",			/* 96 = xfspioctl */
	"clock_gettime",			/* 97 = clock_gettime */
	"clock_settime",			/* 98 = clock_settime */
	"clock_getres",			/* 99 = clock_getres */
	"#100 (unimplemented timer_create)",		/* 100 = unimplemented timer_create */
	"#101 (unimplemented timer_delete)",		/* 101 = unimplemented timer_delete */
	"#102 (unimplemented timer_settime)",		/* 102 = unimplemented timer_settime */
	"#103 (unimplemented timer_gettime)",		/* 103 = unimplemented timer_gettime */
	"#104 (unimplemented timer_getoverrun)",		/* 104 = unimplemented timer_getoverrun */
	"mmap",			/* 105 = mmap */
	"munmap",			/* 106 = munmap */
	"mprotect",			/* 107 = mprotect */
	"madvise",			/* 108 = madvise */
	"mincore",			/* 109 = mincore */
	"mlock",			/* 110 = mlock */
	"munlock",			/* 111 = munlock */
	"mlockall",			/* 112 = mlockall */
	"munlockall",			/* 113 = munlockall */
	"minherit",			/* 114 = minherit */
	"msync",			/* 115 = msync */
	"mquery",			/* 116 = mquery */
	"nanosleep",			/* 117 = nanosleep */
	"poll",			/* 118 = poll */
	"select",			/* 119 = select */
	"pipe",			/* 120 = pipe */
	"kqueue",			/* 121 = kqueue */
	"kevent",			/* 122 = kevent */
	"getresuid",			/* 123 = getresuid */
	"setresuid",			/* 124 = setresuid */
	"getresgid",			/* 125 = getresgid */
	"setresgid",			/* 126 = setresgid */
	"getfsstat",			/* 127 = getfsstat */
	"fstatfs",			/* 128 = fstatfs */
	"#129 (unimplemented)",		/* 129 = unimplemented */
	"#130 (unimplemented aio_open)",		/* 130 = unimplemented aio_open */
	"#131 (unimplemented aio_read)",		/* 131 = unimplemented aio_read */
	"#132 (unimplemented aio_write)",		/* 132 = unimplemented aio_write */
	"#133 (unimplemented aio_fsync)",		/* 133 = unimplemented aio_fsync */
	"#134 (unimplemented aio_stat)",		/* 134 = unimplemented aio_stat */
	"#135 (unimplemented aio_wstat)",		/* 135 = unimplemented aio_wstat */
	"#136 (unimplemented aio_close)",		/* 136 = unimplemented aio_close */
	"#137 (unimplemented aio_return)",		/* 137 = unimplemented aio_return */
	"#138 (unimplemented aio_cancel)",		/* 138 = unimplemented aio_cancel */
	"#139 (unimplemented)",		/* 139 = unimplemented */
	"#140 (unimplemented)",		/* 140 = unimplemented */
	"#141 (unimplemented)",		/* 141 = unimplemented */
	"#142 (unimplemented)",		/* 142 = unimplemented */
	"#143 (unimplemented)",		/* 143 = unimplemented */
	"#144 (unimplemented)",		/* 144 = unimplemented */
	"#145 (unimplemented)",		/* 145 = unimplemented */
	"#146 (unimplemented)",		/* 146 = unimplemented */
	"#147 (unimplemented)",		/* 147 = unimplemented */
	"#148 (unimplemented)",		/* 148 = unimplemented */
	"#149 (unimplemented)",		/* 149 = unimplemented */
	"#150 (unimplemented)",		/* 150 = unimplemented */
	"#151 (unimplemented)",		/* 151 = unimplemented */
	"#152 (unimplemented)",		/* 152 = unimplemented */
	"#153 (unimplemented)",		/* 153 = unimplemented */
	"#154 (unimplemented)",		/* 154 = unimplemented */
	"#155 (unimplemented)",		/* 155 = unimplemented */
	"#156 (unimplemented)",		/* 156 = unimplemented */
	"#157 (unimplemented)",		/* 157 = unimplemented */
	"#158 (unimplemented)",		/* 158 = unimplemented */
	"#159 (unimplemented)",		/* 159 = unimplemented */
	"#160 (unimplemented sys_extattrctl)",		/* 160 = unimplemented sys_extattrctl */
	"#161 (unimplemented sys_extattr_set_file)",		/* 161 = unimplemented sys_extattr_set_file */
	"#162 (unimplemented sys_extattr_get_file)",		/* 162 = unimplemented sys_extattr_get_file */
	"#163 (unimplemented sys_extattr_delete_file)",		/* 163 = unimplemented sys_extattr_delete_file */
	"#164 (unimplemented sys_extattr_set_fd)",		/* 164 = unimplemented sys_extattr_set_fd */
	"#165 (unimplemented sys_extattr_get_fd)",		/* 165 = unimplemented sys_extattr_get_fd */
	"#166 (unimplemented sys_extattr_delete_fd)",		/* 166 = unimplemented sys_extattr_delete_fd */
#if defined(NFSCLIENT) || defined(NFSSERVER)
	"nfssvc",			/* 167 = nfssvc */
#else
	"#167 (unimplemented)",		/* 167 = unimplemented */
#endif
#ifdef ACCOUNTING
	"acct",			/* 168 = acct */
#else
	"#168 (unimplemented acct)",		/* 168 = unimplemented acct */
#endif
#ifdef PTRACE
	"ptrace",			/* 169 = ptrace */
#else
	"#169 (unimplemented ptrace)",		/* 169 = unimplemented ptrace */
#endif
#ifdef KTRACE
	"ktrace",			/* 170 = ktrace */
#else
	"#170 (unimplemented ktrace)",		/* 170 = unimplemented ktrace */
#endif
#ifdef SYSVSEM
	"semget",			/* 171 = semget */
	"semop",			/* 172 = semop */
	"__semctl",			/* 173 = __semctl */
#else
	"#171 (unimplemented semget)",		/* 171 = unimplemented semget */
	"#172 (unimplemented semop)",		/* 172 = unimplemented semop */
	"#173 (unimplemented ___semctl)",		/* 173 = unimplemented ___semctl */
#endif
#ifdef SYSVSHM
	"shmget",			/* 174 = shmget */
	"shmctl",			/* 175 = shmctl */
	"shmat",			/* 176 = shmat */
	"shmdt",			/* 177 = shmdt */
#else
	"#174 (unimplemented shmget)",		/* 174 = unimplemented shmget */
	"#175 (unimplemented shmctl)",		/* 175 = unimplemented shmctl */
	"#176 (unimplemented shmat)",		/* 176 = unimplemented shmat */
	"#177 (unimplemented shmdt)",		/* 177 = unimplemented shmdt */
#endif
#ifdef SYSVMSG
	"msgget",			/* 178 = msgget */
	"msgsnd",			/* 179 = msgsnd */
	"msgrcv",			/* 180 = msgrcv */
	"msgctl",			/* 181 = msgctl */
#else
	"#178 (unimplemented msgget)",		/* 178 = unimplemented msgget */
	"#179 (unimplemented msgsnd)",		/* 179 = unimplemented msgsnd */
	"#180 (unimplemented msgrcv)",		/* 180 = unimplemented msgrcv */
	"#181 (unimplemented msgctl)",		/* 181 = unimplemented msgctl */
#endif
#ifdef RTHREADS
	"getthrid",			/* 182 = getthrid */
	"thrsleep",			/* 183 = thrsleep */
	"thrwakeup",			/* 184 = thrwakeup */
	"threxit",			/* 185 = threxit */
	"thrsigdivert",			/* 186 = thrsigdivert */
#else
	"#182 (unimplemented)",		/* 182 = unimplemented */
	"#183 (unimplemented)",		/* 183 = unimplemented */
	"#184 (unimplemented)",		/* 184 = unimplemented */
	"#185 (unimplemented)",		/* 185 = unimplemented */
	"#186 (unimplemented)",		/* 186 = unimplemented */
#endif
	"#187 (unimplemented)",		/* 187 = unimplemented */
	"#188 (unimplemented)",		/* 188 = unimplemented */
	"#189 (unimplemented)",		/* 189 = unimplemented */
#ifdef LKM
	"lkmnosys",			/* 190 = lkmnosys */
	"lkmnosys",			/* 191 = lkmnosys */
	"lkmnosys",			/* 192 = lkmnosys */
	"lkmnosys",			/* 193 = lkmnosys */
	"lkmnosys",			/* 194 = lkmnosys */
	"lkmnosys",			/* 195 = lkmnosys */
	"lkmnosys",			/* 196 = lkmnosys */
	"lkmnosys",			/* 197 = lkmnosys */
#else	/* !LKM */
	"#190 (unimplemented)",		/* 190 = unimplemented */
	"#191 (unimplemented)",		/* 191 = unimplemented */
	"#192 (unimplemented)",		/* 192 = unimplemented */
	"#193 (unimplemented)",		/* 193 = unimplemented */
	"#194 (unimplemented)",		/* 194 = unimplemented */
	"#195 (unimplemented)",		/* 195 = unimplemented */
	"#196 (unimplemented)",		/* 196 = unimplemented */
	"#197 (unimplemented)",		/* 197 = unimplemented */
#endif	/* !LKM */
	"__syscall",			/* 198 = __syscall */
	"#199 (unimplemented)",		/* 199 = unimplemented */
	"#200 (unimplemented)",		/* 200 = unimplemented */
	"#201 (unimplemented)",		/* 201 = unimplemented */
	"#202 (unimplemented)",		/* 202 = unimplemented */
	"#203 (unimplemented)",		/* 203 = unimplemented */
	"#204 (unimplemented)",		/* 204 = unimplemented */
	"#205 (unimplemented)",		/* 205 = unimplemented */
	"#206 (unimplemented)",		/* 206 = unimplemented */
	"#207 (unimplemented)",		/* 207 = unimplemented */
	"#208 (unimplemented)",		/* 208 = unimplemented */
	"#209 (unimplemented)",		/* 209 = unimplemented */
	"#210 (unimplemented)",		/* 210 = unimplemented */
	"#211 (unimplemented)",		/* 211 = unimplemented */
	"#212 (unimplemented)",		/* 212 = unimplemented */
	"#213 (unimplemented)",		/* 213 = unimplemented */
	"#214 (unimplemented)",		/* 214 = unimplemented */
	"#215 (unimplemented)",		/* 215 = unimplemented */
	"#216 (unimplemented)",		/* 216 = unimplemented */
	"#217 (unimplemented)",		/* 217 = unimplemented */
	"#218 (unimplemented)",		/* 218 = unimplemented */
	"#219 (unimplemented)",		/* 219 = unimplemented */
	"fhstatfs",			/* 220 = fhstatfs */
	"getfh",			/* 221 = getfh */
	"fhopen",			/* 222 = fhopen */
	"fhstat",			/* 223 = fhstat */
	"open",			/* 224 = open */
	"read",			/* 225 = read */
	"write",			/* 226 = write */
	"readv",			/* 227 = readv */
	"writev",			/* 228 = writev */
	"pread",			/* 229 = pread */
	"pwrite",			/* 230 = pwrite */
	"preadv",			/* 231 = preadv */
	"pwritev",			/* 232 = pwritev */
	"fsync",			/* 233 = fsync */
	"fstat",			/* 234 = fstat */
	"ftruncate",			/* 235 = ftruncate */
	"futimes",			/* 236 = futimes */
	"fchmod",			/* 237 = fchmod */
	"fchown",			/* 238 = fchown */
	"fchflags",			/* 239 = fchflags */
	"close",			/* 240 = close */
	"chdir",			/* 241 = chdir */
	"pathconf",			/* 242 = pathconf */
	"access",			/* 243 = access */
	"stat",			/* 244 = stat */
	"lstat",			/* 245 = lstat */
	"statfs",			/* 246 = statfs */
	"truncate",			/* 247 = truncate */
	"utimes",			/* 248 = utimes */
	"chmod",			/* 249 = chmod */
	"chown",			/* 250 = chown */
	"lchown",			/* 251 = lchown */
	"chflags",			/* 252 = chflags */
	"fcntl",			/* 253 = fcntl */
};
