
PROG=	authpf
MAN=	authpf.8

LINKS=  ${BINDIR}/authpf ${BINDIR}/authpf-noip
MLINKS+=authpf.8 authpf-noip.8

BINOWN= root
BINGRP= authpf
BINMODE= 6555
SRCS=	authpf.c
CFLAGS+= -Wall

.include <bsd.prog.mk>
