.\"
.\" Copyright (C) 1985, 1993, 1994
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Copyright (C) Caldera International Inc.  2001-2002.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code and documentation must retain the above
.\"    copyright notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed or owned by Caldera
.\"	International, Inc.
.\" 4. Neither the name of Caldera International, Inc. nor the names of other
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\"
.\" USE OF THE SOFTWARE PROVIDED FOR UNDER THIS LICENSE BY CALDERA
.\" INTERNATIONAL, INC. AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL CALDERA INTERNATIONAL, INC. BE LIABLE FOR ANY DIRECT,
.\" INDIRECT INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
.\" IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	@(#)plot.1	8.1 (Berkeley) 6/6/93
.\"
.Dd $Mdocdate: March 3 2011 $
.Dt PLOT 1
.Os
.Sh NAME
.Nm plot
.Nd graphics filters
.Sh SYNOPSIS
.Nm plot
.Op Fl T Ar terminal
.Op Fl r Ar resolution
.Ar
.Sh DESCRIPTION
These command reads plotting instructions (see
.Xr plot 5 )
from the standard input or the specified
.Ar files ,
and in general produce plotting instructions suitable for
a particular
.Ar terminal
on the standard output.
The
.Fl r
flag may be used to specify the device's output resolution
(currently only the Imagen laser printer understands this option).
.Pp
If no
.Ar terminal
type is specified, the environment parameter
.Ev $TERM
(see
.Xr environ 7 )
is used.
Known
.Ar terminals
are:
.Bl -tag -width indent
.It Cm 4013
Tektronix 4013 storage scope.
.It Cm 4014 No \&or Cm tek
Tektronix 4014 or 4015 storage scope with Enhanced Graphics Module.
(Use 4013 for Tektronix 4014 or 4015 without the Enhanced Graphics Module).
.It Cm 450
.Tn DASI
Hyterm 450 terminal (Diablo mechanism).
.It Cm 300
.Tn DASI
300 or
.Tn GSI
terminal (Diablo mechanism).
.It Cm 300S
DASI 300S terminal (Diablo mechanism).
.It Cm aed
.Tn AED
512 color graphics terminal.
.It Cm bitgraph No \&or Cm bg
.Tn BBN
bitgraph graphics terminal.
.It Cm imagen No \&or Cm \&ip
Imagen laser printer (default 240 dots-per-inch resolution).
.It Cm crt
Any crt terminal capable of running
.Xr vi  1  .
.It Cm dumb
Dumb terminals without cursor addressing or line printers.
.It Cm vt125
DEC vt125 terminal.
.It Xo
.Cm hp2648 No \&or Cm \&hp
.No \&or Cm hp8
.Xc
Hewlett Packard 2648 graphics terminal.
.It Cm ver
Versatec D1200A printer-plotter.
.It Cm var
Benson Varian printer-plotter.
.It Cm xterm
.Tn X11
.Xr xterm 1
flavour of the DEC vt220 terminal (a synonym for
.Cm 4014
and
.Cm tek ).
.El
.Pp
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev TERM
Used to determine the terminal type if not given as an argument.
.Sh FILES
.Bl -tag -width /usr/bin/gigiplot -compact
.It Pa /usr/share/misc/plotcap
.It Pa /usr/bin/lpr
.El
.Sh SEE ALSO
.Xr graph 1 ,
.Xr lpr 1 ,
.Xr plot 3 ,
.Xr plot 5 ,
.Xr plotcap 5 ,
.Xr term 7
.Sh HISTORY
The
.Nm plot
command appeared in
.At v6 .
