.\" Copyright (c) 2009 Marc Balmer <marc@msys.ch>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GPIOSIM 4
.Os
.Sh NAME
.Nm gpiosim
.Nd GPIO simulator device
.Sh SYNOPSIS
.Cd "gpiosim* at gpio?"
.Sh DESCRIPTION
The
.Nm
driver provides a GPIO simulator.
Besides the
.Xr gpio 4
interface, the internal state of the simulated gpio device can
be manipulated using the
.Xr bio 4
indirect method of ioctls.
The number of pins is fixed at 32.
.Sh SEE ALSO
.Xr gpio 4 ,
.Xr intro 4 ,
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 4.5 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Marc Balmer Aq marc@msys.ch .
