.\"
.\" Michael Shalayeff, 2009. Public Domain.
.\"
.Dd $Mdocdate: September 14 2009 $
.Dt KSZPHY 4
.Os
.Sh NAME
.Nm kszphy
.Nd Micrel KSZ8041NL 10/100 Ethernet PHY
.Sh SYNOPSIS
.Cd "kszphy* at mii?"
.Sh DESCRIPTION
The
.Nm
driver supports the Micrel KSZ8041NL 10/100 PHY.
.Pp
This low-power PHY is typically used on all sorts of embedded
and mobile devices.
.Sh SEE ALSO
.Xr ifmedia 4 ,
.Xr intro 4 ,
.Xr mii 4 ,
.Xr ifconfig 8
