
LIB=I77
SRCS=	backspace.c dfe.c due.c iio.c inquire.c lib.c rewind.c rsfe.c rdfmt.c \
	sue.c uio.c wsfe.c sfe.c fmt.c lio.c lread.c open.c close.c \
	util.c endfile.c wrtfmt.c err.c fmtlib.c
CPPFLAGS+=-I${.CURDIR}
NOMAN=

.include <bsd.lib.mk>
