/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 *
 * created from
 *	ABSD: syscalls.master,v 1.4 2010/02/12 14:25:06 mickey Exp 
 */

/* syscall: "syscall" ret: "int" args: */
#define	OPENBSD_SYS_syscall	0

/* syscall: "exit" ret: "void" args: "int" */
#define	OPENBSD_SYS_exit	1

/* syscall: "fork" ret: "int" args: */
#define	OPENBSD_SYS_fork	2

/* syscall: "read" ret: "ssize_t" args: "int" "void *" "size_t" */
#define	OPENBSD_SYS_read	3

/* syscall: "write" ret: "ssize_t" args: "int" "const void *" "size_t" */
#define	OPENBSD_SYS_write	4

/* syscall: "open" ret: "int" args: "char *" "int" "..." */
#define	OPENBSD_SYS_open	5

/* syscall: "close" ret: "int" args: "int" */
#define	OPENBSD_SYS_close	6

/* syscall: "wait4" ret: "pid_t" args: "pid_t" "int *" "int" "struct rusage *" */
#define	OPENBSD_SYS_wait4	7

				/* 8 is obsolete ocreat */
/* syscall: "link" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_link	9

/* syscall: "unlink" ret: "int" args: "char *" */
#define	OPENBSD_SYS_unlink	10

				/* 11 is obsolete execv */
/* syscall: "chdir" ret: "int" args: "char *" */
#define	OPENBSD_SYS_chdir	12

/* syscall: "fchdir" ret: "int" args: "int" */
#define	OPENBSD_SYS_fchdir	13

/* syscall: "mknod" ret: "int" args: "char *" "mode_t" "dev_t" */
#define	OPENBSD_SYS_mknod	14

/* syscall: "chmod" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_chmod	15

/* syscall: "chown" ret: "int" args: "char *" "uid_t" "gid_t" */
#define	OPENBSD_SYS_chown	16

/* syscall: "break" ret: "int" args: "char *" */
#define	OPENBSD_SYS_break	17

				/* 18 is obsolete 2.5 ogetfsstat */
				/* 19 is obsolete olseek */
/* syscall: "getpid" ret: "pid_t" args: */
#define	OPENBSD_SYS_getpid	20

/* syscall: "mount" ret: "int" args: "char *" "char *" "int" "void *" */
#define	OPENBSD_SYS_mount	21

/* syscall: "unmount" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_unmount	22

/* syscall: "setuid" ret: "int" args: "uid_t" */
#define	OPENBSD_SYS_setuid	23

/* syscall: "getuid" ret: "uid_t" args: */
#define	OPENBSD_SYS_getuid	24

/* syscall: "geteuid" ret: "uid_t" args: */
#define	OPENBSD_SYS_geteuid	25

/* syscall: "ptrace" ret: "int" args: "int" "pid_t" "caddr_t" "int" */
#define	OPENBSD_SYS_ptrace	26

/* syscall: "recvmsg" ret: "ssize_t" args: "int" "struct msghdr *" "int" */
#define	OPENBSD_SYS_recvmsg	27

/* syscall: "sendmsg" ret: "ssize_t" args: "int" "const struct msghdr *" "int" */
#define	OPENBSD_SYS_sendmsg	28

/* syscall: "recvfrom" ret: "ssize_t" args: "int" "void *" "size_t" "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_recvfrom	29

/* syscall: "accept" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_accept	30

/* syscall: "getpeername" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_getpeername	31

/* syscall: "getsockname" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_getsockname	32

/* syscall: "access" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_access	33

/* syscall: "chflags" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_chflags	34

/* syscall: "fchflags" ret: "int" args: "int" "u_int" */
#define	OPENBSD_SYS_fchflags	35

/* syscall: "sync" ret: "void" args: */
#define	OPENBSD_SYS_sync	36

/* syscall: "kill" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_kill	37

				/* 38 is obsolete stat43 */
/* syscall: "getppid" ret: "pid_t" args: */
#define	OPENBSD_SYS_getppid	39

				/* 40 is obsolete lstat43 */
/* syscall: "dup" ret: "int" args: "int" */
#define	OPENBSD_SYS_dup	41

/* syscall: "opipe" ret: "int" args: */
#define	OPENBSD_SYS_opipe	42

/* syscall: "getegid" ret: "gid_t" args: */
#define	OPENBSD_SYS_getegid	43

/* syscall: "profil" ret: "int" args: "caddr_t" "size_t" "u_long" "u_int" */
#define	OPENBSD_SYS_profil	44

/* syscall: "ktrace" ret: "int" args: "const char *" "int" "int" "pid_t" */
#define	OPENBSD_SYS_ktrace	45

/* syscall: "sigaction" ret: "int" args: "int" "const struct sigaction *" "struct sigaction *" */
#define	OPENBSD_SYS_sigaction	46

/* syscall: "getgid" ret: "gid_t" args: */
#define	OPENBSD_SYS_getgid	47

/* syscall: "sigprocmask" ret: "int" args: "int" "sigset_t" */
#define	OPENBSD_SYS_sigprocmask	48

/* syscall: "getlogin" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_getlogin	49

/* syscall: "setlogin" ret: "int" args: "const char *" */
#define	OPENBSD_SYS_setlogin	50

/* syscall: "sigpending" ret: "int" args: */
#define	OPENBSD_SYS_sigpending	52

/* syscall: "osigaltstack" ret: "int" args: "const struct osigaltstack *" "struct osigaltstack *" */
#define	OPENBSD_SYS_osigaltstack	53

/* syscall: "ioctl" ret: "int" args: "int" "u_long" "..." */
#define	OPENBSD_SYS_ioctl	54

/* syscall: "reboot" ret: "int" args: "int" */
#define	OPENBSD_SYS_reboot	55

/* syscall: "revoke" ret: "int" args: "char *" */
#define	OPENBSD_SYS_revoke	56

/* syscall: "symlink" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_symlink	57

/* syscall: "readlink" ret: "int" args: "char *" "char *" "size_t" */
#define	OPENBSD_SYS_readlink	58

/* syscall: "execve" ret: "int" args: "char *" "char *const *" "char *const *" */
#define	OPENBSD_SYS_execve	59

/* syscall: "umask" ret: "mode_t" args: "mode_t" */
#define	OPENBSD_SYS_umask	60

/* syscall: "chroot" ret: "int" args: "char *" */
#define	OPENBSD_SYS_chroot	61

				/* 62 is obsolete fstat43 */
				/* 63 is obsolete ogetkerninfo */
				/* 64 is obsolete ogetpagesize */
				/* 65 is obsolete 2.5 omsync */
/* syscall: "vfork" ret: "int" args: */
#define	OPENBSD_SYS_vfork	66

				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */
				/* 69 is obsolete sbrk */
				/* 70 is obsolete sstk */
				/* 71 is obsolete ommap */
				/* 72 is obsolete vadvise */
/* syscall: "munmap" ret: "int" args: "void *" "size_t" */
#define	OPENBSD_SYS_munmap	73

/* syscall: "mprotect" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_mprotect	74

/* syscall: "madvise" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_madvise	75

				/* 76 is obsolete vhangup */
				/* 77 is obsolete vlimit */
/* syscall: "mincore" ret: "int" args: "void *" "size_t" "char *" */
#define	OPENBSD_SYS_mincore	78

/* syscall: "getgroups" ret: "int" args: "int" "gid_t *" */
#define	OPENBSD_SYS_getgroups	79

/* syscall: "setgroups" ret: "int" args: "int" "const gid_t *" */
#define	OPENBSD_SYS_setgroups	80

/* syscall: "getpgrp" ret: "int" args: */
#define	OPENBSD_SYS_getpgrp	81

/* syscall: "setpgid" ret: "int" args: "pid_t" "int" */
#define	OPENBSD_SYS_setpgid	82

/* syscall: "setitimer" ret: "int" args: "int" "const struct itimerval *" "struct itimerval *" */
#define	OPENBSD_SYS_setitimer	83

				/* 84 is obsolete owait */
				/* 85 is obsolete 2.5 swapon */
/* syscall: "getitimer" ret: "int" args: "int" "struct itimerval *" */
#define	OPENBSD_SYS_getitimer	86

				/* 87 is obsolete ogethostname */
				/* 88 is obsolete osethostname */
				/* 89 is obsolete ogetdtablesize */
/* syscall: "dup2" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_dup2	90

/* syscall: "fcntl" ret: "int" args: "int" "int" "..." */
#define	OPENBSD_SYS_fcntl	92

/* syscall: "select" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "struct timeval *" */
#define	OPENBSD_SYS_select	93

/* syscall: "fsync" ret: "int" args: "int" */
#define	OPENBSD_SYS_fsync	95

/* syscall: "setpriority" ret: "int" args: "int" "id_t" "int" */
#define	OPENBSD_SYS_setpriority	96

/* syscall: "socket" ret: "int" args: "int" "int" "int" */
#define	OPENBSD_SYS_socket	97

/* syscall: "connect" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_connect	98

				/* 99 is obsolete oaccept */
/* syscall: "getpriority" ret: "int" args: "int" "id_t" */
#define	OPENBSD_SYS_getpriority	100

				/* 101 is obsolete osend */
				/* 102 is obsolete orecv */
/* syscall: "sigreturn" ret: "int" args: "struct sigcontext *" */
#define	OPENBSD_SYS_sigreturn	103

/* syscall: "bind" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_bind	104

/* syscall: "setsockopt" ret: "int" args: "int" "int" "int" "const void *" "socklen_t" */
#define	OPENBSD_SYS_setsockopt	105

/* syscall: "listen" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_listen	106

				/* 107 is obsolete vtimes */
				/* 108 is obsolete osigvec */
				/* 109 is obsolete osigblock */
				/* 110 is obsolete osigsetmask */
/* syscall: "sigsuspend" ret: "int" args: "int" */
#define	OPENBSD_SYS_sigsuspend	111

				/* 112 is obsolete osigstack */
				/* 113 is obsolete orecvmsg */
				/* 114 is obsolete osendmsg */
				/* 115 is obsolete vtrace */
/* syscall: "gettimeofday" ret: "int" args: "struct timeval *" "struct timezone *" */
#define	OPENBSD_SYS_gettimeofday	116

/* syscall: "getrusage" ret: "int" args: "int" "struct rusage *" */
#define	OPENBSD_SYS_getrusage	117

/* syscall: "getsockopt" ret: "int" args: "int" "int" "int" "void *" "socklen_t *" */
#define	OPENBSD_SYS_getsockopt	118

				/* 119 is obsolete resuba */
/* syscall: "readv" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	OPENBSD_SYS_readv	120

/* syscall: "writev" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	OPENBSD_SYS_writev	121

/* syscall: "settimeofday" ret: "int" args: "const struct timeval *" "const struct timezone *" */
#define	OPENBSD_SYS_settimeofday	122

/* syscall: "fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	OPENBSD_SYS_fchown	123

/* syscall: "fchmod" ret: "int" args: "int" "mode_t" */
#define	OPENBSD_SYS_fchmod	124

				/* 125 is obsolete orecvfrom */
/* syscall: "setreuid" ret: "int" args: "uid_t" "uid_t" */
#define	OPENBSD_SYS_setreuid	126

/* syscall: "setregid" ret: "int" args: "gid_t" "gid_t" */
#define	OPENBSD_SYS_setregid	127

/* syscall: "rename" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_rename	128

				/* 129 is obsolete otruncate */
				/* 130 is obsolete oftruncate */
/* syscall: "flock" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_flock	131

/* syscall: "mkfifo" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_mkfifo	132

/* syscall: "sendto" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_sendto	133

/* syscall: "shutdown" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_shutdown	134

/* syscall: "socketpair" ret: "int" args: "int" "int" "int" "int *" */
#define	OPENBSD_SYS_socketpair	135

/* syscall: "mkdir" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_mkdir	136

/* syscall: "rmdir" ret: "int" args: "char *" */
#define	OPENBSD_SYS_rmdir	137

/* syscall: "utimes" ret: "int" args: "char *" "const struct timeval *" */
#define	OPENBSD_SYS_utimes	138

				/* 139 is obsolete 4.2 sigreturn */
/* syscall: "adjtime" ret: "int" args: "const struct timeval *" "struct timeval *" */
#define	OPENBSD_SYS_adjtime	140

				/* 141 is obsolete ogetpeername */
				/* 142 is obsolete ogethostid */
				/* 143 is obsolete osethostid */
				/* 144 is obsolete ogetrlimit */
				/* 145 is obsolete osetrlimit */
				/* 146 is obsolete okillpg */
/* syscall: "setsid" ret: "int" args: */
#define	OPENBSD_SYS_setsid	147

/* syscall: "quotactl" ret: "int" args: "const char *" "int" "int" "char *" */
#define	OPENBSD_SYS_quotactl	148

				/* 149 is obsolete oquota */
				/* 150 is obsolete ogetsockname */
/* syscall: "nfssvc" ret: "int" args: "int" "void *" */
#define	OPENBSD_SYS_nfssvc	155

				/* 156 is obsolete ogetdirentries */
				/* 157 is obsolete 2.5 ostatfs */
				/* 158 is obsolete 2.5 ostatfs */
/* syscall: "getfh" ret: "int" args: "char *" "fhandle_t *" */
#define	OPENBSD_SYS_getfh	161

				/* 162 is obsolete 0.9 ogetdomainname */
				/* 163 is obsolete 0.9 osetdomainname */
/* syscall: "sysarch" ret: "int" args: "int" "void *" */
#define	OPENBSD_SYS_sysarch	165

				/* 169 is obsolete 1.0 semsys */
				/* 170 is obsolete 1.0 msgsys */
				/* 171 is obsolete 1.0 shmsys */
/* syscall: "pread" ret: "ssize_t" args: "int" "void *" "size_t" "int" "off_t" */
#define	OPENBSD_SYS_pread	173

/* syscall: "pwrite" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "off_t" */
#define	OPENBSD_SYS_pwrite	174

/* syscall: "setgid" ret: "int" args: "gid_t" */
#define	OPENBSD_SYS_setgid	181

/* syscall: "setegid" ret: "int" args: "gid_t" */
#define	OPENBSD_SYS_setegid	182

/* syscall: "seteuid" ret: "int" args: "uid_t" */
#define	OPENBSD_SYS_seteuid	183

/* syscall: "lfs_bmapv" ret: "int" args: "fsid_t *" "struct block_info *" "int" */
#define	OPENBSD_SYS_lfs_bmapv	184

/* syscall: "lfs_markv" ret: "int" args: "fsid_t *" "struct block_info *" "int" */
#define	OPENBSD_SYS_lfs_markv	185

/* syscall: "lfs_segclean" ret: "int" args: "fsid_t *" "u_long" */
#define	OPENBSD_SYS_lfs_segclean	186

/* syscall: "lfs_segwait" ret: "int" args: "fsid_t *" "struct timeval *" */
#define	OPENBSD_SYS_lfs_segwait	187

				/* 188 is obsolete stat35 */
				/* 189 is obsolete fstat35 */
				/* 190 is obsolete lstat35 */
/* syscall: "pathconf" ret: "long" args: "char *" "int" */
#define	OPENBSD_SYS_pathconf	191

/* syscall: "fpathconf" ret: "long" args: "int" "int" */
#define	OPENBSD_SYS_fpathconf	192

/* syscall: "swapctl" ret: "int" args: "int" "const void *" "int" */
#define	OPENBSD_SYS_swapctl	193

/* syscall: "getrlimit" ret: "int" args: "int" "struct rlimit *" */
#define	OPENBSD_SYS_getrlimit	194

/* syscall: "setrlimit" ret: "int" args: "int" "const struct rlimit *" */
#define	OPENBSD_SYS_setrlimit	195

/* syscall: "getdirentries" ret: "int" args: "int" "char *" "int" "long *" */
#define	OPENBSD_SYS_getdirentries	196

/* syscall: "mmap" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	OPENBSD_SYS_mmap	197

/* syscall: "__syscall" ret: "quad_t" args: "quad_t" "..." */
#define	OPENBSD_SYS___syscall	198

/* syscall: "lseek" ret: "off_t" args: "int" "int" "off_t" "int" */
#define	OPENBSD_SYS_lseek	199

/* syscall: "truncate" ret: "int" args: "char *" "int" "off_t" */
#define	OPENBSD_SYS_truncate	200

/* syscall: "ftruncate" ret: "int" args: "int" "int" "off_t" */
#define	OPENBSD_SYS_ftruncate	201

/* syscall: "__sysctl" ret: "int" args: "int *" "u_int" "void *" "size_t *" "void *" "size_t" */
#define	OPENBSD_SYS___sysctl	202

/* syscall: "mlock" ret: "int" args: "const void *" "size_t" */
#define	OPENBSD_SYS_mlock	203

/* syscall: "munlock" ret: "int" args: "const void *" "size_t" */
#define	OPENBSD_SYS_munlock	204

/* syscall: "futimes" ret: "int" args: "int" "const struct timeval *" */
#define	OPENBSD_SYS_futimes	206

/* syscall: "getpgid" ret: "pid_t" args: "pid_t" */
#define	OPENBSD_SYS_getpgid	207

/* syscall: "xfspioctl" ret: "int" args: "int" "char *" "int" "struct ViceIoctl *" "int" */
#define	OPENBSD_SYS_xfspioctl	208

				/* 220 is obsolete semctl23 */
/* syscall: "semget" ret: "int" args: "key_t" "int" "int" */
#define	OPENBSD_SYS_semget	221

				/* 222 is obsolete 3.5 semop */
				/* 223 is obsolete semconfig */
				/* 224 is obsolete msgctl23 */
/* syscall: "msgget" ret: "int" args: "key_t" "int" */
#define	OPENBSD_SYS_msgget	225

/* syscall: "msgsnd" ret: "int" args: "int" "const void *" "size_t" "int" */
#define	OPENBSD_SYS_msgsnd	226

/* syscall: "msgrcv" ret: "int" args: "int" "void *" "size_t" "long" "int" */
#define	OPENBSD_SYS_msgrcv	227

/* syscall: "shmat" ret: "void *" args: "int" "const void *" "int" */
#define	OPENBSD_SYS_shmat	228

				/* 229 is obsolete shmctl23 */
/* syscall: "shmdt" ret: "int" args: "const void *" */
#define	OPENBSD_SYS_shmdt	230

				/* 231 is obsolete 3.5 shmget */
/* syscall: "clock_gettime" ret: "int" args: "clockid_t" "struct timespec *" */
#define	OPENBSD_SYS_clock_gettime	232

/* syscall: "clock_settime" ret: "int" args: "clockid_t" "const struct timespec *" */
#define	OPENBSD_SYS_clock_settime	233

/* syscall: "clock_getres" ret: "int" args: "clockid_t" "struct timespec *" */
#define	OPENBSD_SYS_clock_getres	234

/* syscall: "nanosleep" ret: "int" args: "const struct timespec *" "struct timespec *" */
#define	OPENBSD_SYS_nanosleep	240

/* syscall: "minherit" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_minherit	250

/* syscall: "rfork" ret: "int" args: "int" */
#define	OPENBSD_SYS_rfork	251

/* syscall: "poll" ret: "int" args: "struct pollfd *" "u_int" "int" */
#define	OPENBSD_SYS_poll	252

/* syscall: "issetugid" ret: "int" args: */
#define	OPENBSD_SYS_issetugid	253

/* syscall: "lchown" ret: "int" args: "char *" "uid_t" "gid_t" */
#define	OPENBSD_SYS_lchown	254

/* syscall: "getsid" ret: "pid_t" args: "pid_t" */
#define	OPENBSD_SYS_getsid	255

/* syscall: "msync" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_msync	256

				/* 257 is obsolete 3.5 __semctl */
				/* 258 is obsolete 3.5 shmctl */
				/* 259 is obsolete 3.5 msgctl */
				/* 260 is obsolete getfsstat */
				/* 261 is obsolete statfs */
				/* 262 is obsolete fstatfs */
/* syscall: "pipe" ret: "int" args: "int *" */
#define	OPENBSD_SYS_pipe	263

/* syscall: "fhopen" ret: "int" args: "const fhandle_t *" "int" */
#define	OPENBSD_SYS_fhopen	264

				/* 265 is obsolete 3.5 fhstat */
				/* 266 is obsolete fhstatfs */
/* syscall: "preadv" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	OPENBSD_SYS_preadv	267

/* syscall: "pwritev" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	OPENBSD_SYS_pwritev	268

/* syscall: "kqueue" ret: "int" args: */
#define	OPENBSD_SYS_kqueue	269

/* syscall: "kevent" ret: "int" args: "int" "const struct kevent *" "int" "struct kevent *" "int" "const struct timespec *" */
#define	OPENBSD_SYS_kevent	270

/* syscall: "mlockall" ret: "int" args: "int" */
#define	OPENBSD_SYS_mlockall	271

/* syscall: "munlockall" ret: "int" args: */
#define	OPENBSD_SYS_munlockall	272

/* syscall: "getpeereid" ret: "int" args: "int" "uid_t *" "gid_t *" */
#define	OPENBSD_SYS_getpeereid	273

/* syscall: "getresuid" ret: "int" args: "uid_t *" "uid_t *" "uid_t *" */
#define	OPENBSD_SYS_getresuid	281

/* syscall: "setresuid" ret: "int" args: "uid_t" "uid_t" "uid_t" */
#define	OPENBSD_SYS_setresuid	282

/* syscall: "getresgid" ret: "int" args: "gid_t *" "gid_t *" "gid_t *" */
#define	OPENBSD_SYS_getresgid	283

/* syscall: "setresgid" ret: "int" args: "gid_t" "gid_t" "gid_t" */
#define	OPENBSD_SYS_setresgid	284

				/* 285 is obsolete sys_omquery */
/* syscall: "mquery" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	OPENBSD_SYS_mquery	286

/* syscall: "closefrom" ret: "int" args: "int" */
#define	OPENBSD_SYS_closefrom	287

/* syscall: "sigaltstack" ret: "int" args: "const struct sigaltstack *" "struct sigaltstack *" */
#define	OPENBSD_SYS_sigaltstack	288

/* syscall: "shmget" ret: "int" args: "key_t" "size_t" "int" */
#define	OPENBSD_SYS_shmget	289

/* syscall: "semop" ret: "int" args: "int" "struct sembuf *" "size_t" */
#define	OPENBSD_SYS_semop	290

/* syscall: "stat" ret: "int" args: "char *" "struct stat *" */
#define	OPENBSD_SYS_stat	291

/* syscall: "fstat" ret: "int" args: "int" "struct stat *" */
#define	OPENBSD_SYS_fstat	292

/* syscall: "lstat" ret: "int" args: "char *" "struct stat *" */
#define	OPENBSD_SYS_lstat	293

/* syscall: "fhstat" ret: "int" args: "const fhandle_t *" "struct stat *" */
#define	OPENBSD_SYS_fhstat	294

/* syscall: "__semctl" ret: "int" args: "int" "int" "int" "union semun *" */
#define	OPENBSD_SYS___semctl	295

/* syscall: "shmctl" ret: "int" args: "int" "int" "struct shmid_ds *" */
#define	OPENBSD_SYS_shmctl	296

/* syscall: "msgctl" ret: "int" args: "int" "int" "struct msqid_ds *" */
#define	OPENBSD_SYS_msgctl	297

/* syscall: "sched_yield" ret: "int" args: */
#define	OPENBSD_SYS_sched_yield	298

/* syscall: "getthrid" ret: "pid_t" args: */
#define	OPENBSD_SYS_getthrid	299

/* syscall: "thrsleep" ret: "int" args: "void *" "int" "void *" */
#define	OPENBSD_SYS_thrsleep	300

/* syscall: "thrwakeup" ret: "int" args: "void *" "int" */
#define	OPENBSD_SYS_thrwakeup	301

/* syscall: "threxit" ret: "int" args: "int" */
#define	OPENBSD_SYS_threxit	302

/* syscall: "thrsigdivert" ret: "int" args: "sigset_t" */
#define	OPENBSD_SYS_thrsigdivert	303

/* syscall: "__getcwd" ret: "int" args: "char *" "size_t" */
#define	OPENBSD_SYS___getcwd	304

/* syscall: "adjfreq" ret: "int" args: "const int64_t *" "int64_t *" */
#define	OPENBSD_SYS_adjfreq	305

/* syscall: "getfsstat" ret: "int" args: "struct statfs *" "size_t" "int" */
#define	OPENBSD_SYS_getfsstat	306

/* syscall: "statfs" ret: "int" args: "char *" "struct statfs *" */
#define	OPENBSD_SYS_statfs	307

/* syscall: "fstatfs" ret: "int" args: "int" "struct statfs *" */
#define	OPENBSD_SYS_fstatfs	308

/* syscall: "fhstatfs" ret: "int" args: "const fhandle_t *" "struct statfs *" */
#define	OPENBSD_SYS_fhstatfs	309

#define	OPENBSD_SYS_MAXSYSCALL	310
